# Auto-generated by `uv run compile`.
# Do not edit by hand; edit the source trader and recompile.

class __CompiledModule:
    pass

traders = __CompiledModule()
traders.ROUND_3 = __CompiledModule()
traders.ROUND_4 = __CompiledModule()

# --- begin pasted traders/ROUND_3/trader_FLIPVOL.py ---
def __build_trader_FLIPVOL():
    """ROUND_3: trader_ultimate_general — historical-data-first spear.

    This keeps the robust mechanisms from trader_ultimate, but uses priors
    that come from `data/ROUND_3` instead of selecting every constant from a
    single real submission log. Submission logs are smoke checks, not main
    calibration fuel.
    """

    import math
    from dataclasses import dataclass
    from statistics import NormalDist
    from typing import Dict, List, Optional, Tuple

    import jsonpickle

    from datamodel import Order, TradingState


    # ── Black-Scholes (statistics.NormalDist, no scipy needed) ──────────────────

    NORMAL = NormalDist()

    # Time to expiry baked into the BS pricing. Using 1.0 keeps the model
    # numerically stable; the absolute level is absorbed by the smoothed IV.
    TTE = 1.0
    IV_LO, IV_HI = 1e-4, 0.08


    def bs_call(S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return max(S - K, 0.0)
        sqrt_t = math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / (sigma * sqrt_t)
        d2 = d1 - sigma * sqrt_t
        return S * NORMAL.cdf(d1) - K * NORMAL.cdf(d2)


    def bs_vega(S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return 0.0
        sqrt_t = math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / (sigma * sqrt_t)
        return S * NORMAL.pdf(d1) * sqrt_t


    def bs_delta(S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return 1.0 if S > K else 0.0
        sqrt_t = math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / (sigma * sqrt_t)
        return NORMAL.cdf(d1)


    def implied_vol(S: float, K: float, T: float, market_price: float,
                    sigma_init: float = 0.03, iters: int = 30) -> float:
        """Newton-Raphson IV solver, clamped to [IV_LO, IV_HI]."""
        if market_price <= max(S - K, 0.0) + 1e-6:
            return IV_LO
        sigma = sigma_init
        for _ in range(iters):
            diff = bs_call(S, K, T, sigma) - market_price
            if abs(diff) < 1e-6:
                break
            v = bs_vega(S, K, T, sigma)
            if v < 1e-8:
                break
            sigma = max(IV_LO, min(IV_HI, sigma - diff / v))
        return sigma


    # ── Smile shape: IV offset by moneyness (K-S)/100, linear interpolation ─────

    SMILE_KNOTS: Tuple[Tuple[float, float], ...] = (
        (-2.5, -0.0006),
        (-1.5, -0.0012),
        (-0.5, -0.0003),
        (0.5,   0.0),
        (1.5,  -0.0019),
        (2.5,   0.0005),
        (7.5,  -0.0040),
        (12.5, -0.0060),
    )


    def smile_offset(moneyness: float) -> float:
        if moneyness <= SMILE_KNOTS[0][0]:
            return SMILE_KNOTS[0][1]
        if moneyness >= SMILE_KNOTS[-1][0]:
            return SMILE_KNOTS[-1][1]
        for (x0, y0), (x1, y1) in zip(SMILE_KNOTS, SMILE_KNOTS[1:]):
            if x0 <= moneyness <= x1:
                return y0 + (y1 - y0) * (moneyness - x0) / (x1 - x0)
        return 0.0


    # ── Quote helpers ───────────────────────────────────────────────────────────


    @dataclass
    class Quote:
        """Top-of-book + wall-of-book snapshot.

        `wall_mid` averages the highest-volume bid level with the highest-
        volume ask level. The hedgehogs writeup uses this as a more stable
        estimator of true fair than raw (best_bid + best_ask) / 2 — the
        walls are where designated MM bots park their liquidity.
        """
        bid: Optional[int] = None
        bid_vol: int = 0
        ask: Optional[int] = None
        ask_vol: int = 0
        bid_wall: Optional[int] = None
        ask_wall: Optional[int] = None

        @property
        def mid(self) -> Optional[float]:
            if self.bid is None or self.ask is None:
                return None
            return (self.bid + self.ask) / 2.0

        @property
        def wall_mid(self) -> Optional[float]:
            # Fall back to top-of-book if either wall is missing.
            bw = self.bid_wall if self.bid_wall is not None else self.bid
            aw = self.ask_wall if self.ask_wall is not None else self.ask
            if bw is None or aw is None:
                return None
            return (bw + aw) / 2.0

        @property
        def spread(self) -> Optional[int]:
            if self.bid is None or self.ask is None:
                return None
            return self.ask - self.bid


    def quote_from(order_depth) -> Quote:
        q = Quote()
        if order_depth is None:
            return q
        if order_depth.buy_orders:
            q.bid = max(order_depth.buy_orders)
            q.bid_vol = order_depth.buy_orders[q.bid]
            # Wall = level with greatest displayed liquidity.
            q.bid_wall = max(order_depth.buy_orders, key=lambda p: order_depth.buy_orders[p])
        if order_depth.sell_orders:
            q.ask = min(order_depth.sell_orders)
            q.ask_vol = order_depth.sell_orders[q.ask]
            q.ask_wall = min(order_depth.sell_orders, key=lambda p: -order_depth.sell_orders[p])
        return q


    def update_ema(emas: Dict[str, float], key: str, value: float, window: int) -> float:
        if key not in emas:
            emas[key] = value
            return value
        alpha = 2.0 / (window + 1.0)
        emas[key] = alpha * value + (1.0 - alpha) * emas[key]
        return emas[key]


    # ── Per-product config ──────────────────────────────────────────────────────

    VELVET = "VELVETFRUIT_EXTRACT"
    HYDRO = "HYDROGEL_PACK"

    POS_LIMITS = {
        VELVET: 200,
        HYDRO: 200,
        "VEV_4000": 300,
        "VEV_4500": 300,
        "VEV_5000": 300,
        "VEV_5100": 300,
        "VEV_5200": 300,
        "VEV_5300": 300,
        "VEV_5400": 300,
        "VEV_5500": 300,
        "VEV_6000": 300,
        "VEV_6500": 300,
    }


    # ── Trader ──────────────────────────────────────────────────────────────────


    class Trader:
        # ---- state ----
        def load_state(self, td: str) -> Dict:
            default = {
                "emas": {},
                "v_signal_til": -1,
                "vev_dir": 0,
                "vev_dir_til": -1,
                "basket_til": -1,
                "v4_dir": 0,
                "v4_dir_til": -1,
                "prev_S": None,
                "prev_mids": {},
                "cash": {},
                "seen_trades": [],
                "pnl_high": 0.0,
                "option_risk_off": False,
            }
            if not td:
                return default
            try:
                data = jsonpickle.decode(td)
            except Exception:
                return default
            for k, v in default.items():
                data.setdefault(k, v)
            return data

        # ---- order helpers (track in-flight orders to respect position limits) ----
        @staticmethod
        def position(state: TradingState, product: str) -> int:
            return int(state.position.get(product, 0))

        def buy_room(self, state, product, orders) -> int:
            used = sum(o.quantity for o in orders if o.quantity > 0)
            return max(0, POS_LIMITS[product] - self.position(state, product) - used)

        def sell_room(self, state, product, orders) -> int:
            used = sum(-o.quantity for o in orders if o.quantity < 0)
            return max(0, POS_LIMITS[product] + self.position(state, product) - used)

        def buy(self, state, product, orders, price, qty):
            qty = min(max(0, int(qty)), self.buy_room(state, product, orders))
            if qty > 0:
                orders.append(Order(product, int(price), qty))

        def sell(self, state, product, orders, price, qty):
            qty = min(max(0, int(qty)), self.sell_room(state, product, orders))
            if qty > 0:
                orders.append(Order(product, int(price), -qty))

        def mark_pnl(self, state: TradingState, store: Dict) -> float:
            cash = store.setdefault("cash", {})
            seen = set(store.get("seen_trades", []))
            for product, trades in state.own_trades.items():
                for idx, tr in enumerate(trades):
                    # Include list index so identical same-tick fills do not
                    # collapse into one cash event.
                    key = f"{product}:{tr.timestamp}:{idx}:{tr.price}:{tr.quantity}:{tr.buyer}:{tr.seller}"
                    if key in seen:
                        continue
                    seen.add(key)
                    cash.setdefault(product, 0.0)
                    qty = int(tr.quantity)
                    if tr.buyer == "SUBMISSION":
                        cash[product] -= float(tr.price) * qty
                    if tr.seller == "SUBMISSION":
                        cash[product] += float(tr.price) * qty
            store["seen_trades"] = list(seen)[-5000:]

            total = 0.0
            for product, c in cash.items():
                q = quote_from(state.order_depths.get(product))
                if q.mid is not None:
                    total += float(c) + self.position(state, product) * q.mid
            store["pnl_high"] = max(float(store.get("pnl_high", 0.0)), total)
            return total

        def update_low_iv_trail(self, store: Dict, total_pnl: float, smile_lv: float) -> None:
            """Protect option profits only when the surface is in a low-IV regime.

            The public high-PnL dips happened with normal/high IV and later
            recovered. The bad live-style giveback happened after IV was near
            the historical floor. This avoids clock/tick hardcoding.
            """
            high = float(store.get("pnl_high", 0.0))
            drawdown = high - total_pnl
            low_iv = smile_lv < 0.0285
            if high > 100000.0 and drawdown > 2000.0 and low_iv:
                store["option_risk_off"] = True

        def flatten_options(self, state: TradingState, result: Dict[str, List[Order]]) -> None:
            targets = {
                "VEV_4000": -180,
                "VEV_4500": -180,
                "VEV_5000": -220,
                "VEV_5100": -80,
                "VEV_5200": 0,
                "VEV_5300": -220,
                "VEV_5400": -220,
                "VEV_5500": -220,
                "VEV_6000": 0,
                "VEV_6500": 0,
            }
            for product, target in targets.items():
                pos = self.position(state, product)
                delta = target - pos
                if delta == 0:
                    continue
                q = quote_from(state.order_depths.get(product))
                orders = result.setdefault(product, [])
                if delta < 0 and q.bid is not None:
                    self.sell(state, product, orders, q.bid, min(-delta, max(1, q.bid_vol), 40))
                elif delta > 0 and q.ask is not None:
                    self.buy(state, product, orders, q.ask, min(delta, max(1, -q.ask_vol), 40))

        # ---- Signals ----
        def update_signals(self, state: TradingState, store: Dict) -> Tuple[bool, int, bool, int]:
            """Detect:
              (a) VELVET Accumulator: any market trade with quantity >= 9.
              (b) vev_dir: directional score on VEV_5200/5300 trades, but only
                  when BOTH spreads are <= 2 (the alpha-tip filter).
            Both signals decay over time via a TTL stored in `store`.
            """
            for tr in state.market_trades.get(VELVET, []):
                if abs(int(tr.quantity)) >= 9:
                    store["v_signal_til"] = state.timestamp + 1500
                    break

            q5200 = quote_from(state.order_depths.get("VEV_5200"))
            q5300 = quote_from(state.order_depths.get("VEV_5300"))
            tight = (
                q5200.spread is not None and q5200.spread <= 2
                and q5300.spread is not None and q5300.spread <= 2
            )
            if tight:
                score = 0
                for prod in ("VEV_5200", "VEV_5300"):
                    q = quote_from(state.order_depths.get(prod))
                    if q.mid is None:
                        continue
                    for tr in state.market_trades.get(prod, []):
                        px = int(tr.price)
                        n = abs(int(tr.quantity))
                        if q.ask is not None and px >= q.ask:
                            score += n
                        elif q.bid is not None and px <= q.bid:
                            score -= n
                        elif px > q.mid:
                            score += n
                        elif px < q.mid:
                            score -= n
                if score > 0:
                    store["vev_dir"] = 1
                    store["vev_dir_til"] = state.timestamp + 1200
                elif score < 0:
                    store["vev_dir"] = -1
                    store["vev_dir_til"] = state.timestamp + 1200

            basket_hits = sum(
                1
                for prod in ("VEV_5300", "VEV_5400", "VEV_5500", "VEV_6000", "VEV_6500")
                if state.market_trades.get(prod)
            )
            zero_tail_hits = sum(
                1
                for prod in ("VEV_6000", "VEV_6500")
                for tr in state.market_trades.get(prod, [])
                if int(tr.price) == 0
            )
            if basket_hits >= 2:
                store["basket_til"] = state.timestamp + (500 if zero_tail_hits >= 2 else 300)

            q4000 = quote_from(state.order_depths.get("VEV_4000"))
            v4_score = 0
            if q4000.mid is not None:
                for tr in state.market_trades.get("VEV_4000", []):
                    px = int(tr.price)
                    n = abs(int(tr.quantity))
                    if q4000.ask is not None and px >= q4000.ask:
                        v4_score += n
                    elif q4000.bid is not None and px <= q4000.bid:
                        v4_score -= n
                    elif px > q4000.mid:
                        v4_score += n
                    elif px < q4000.mid:
                        v4_score -= n
            if v4_score:
                store["v4_dir"] = 1 if v4_score > 0 else -1
                store["v4_dir_til"] = state.timestamp + 1800

            v_active = state.timestamp <= int(store.get("v_signal_til", -1))
            vev_dir = (
                int(store.get("vev_dir", 0))
                if state.timestamp <= int(store.get("vev_dir_til", -1))
                else 0
            )
            basket_active = state.timestamp <= int(store.get("basket_til", -1))
            v4_dir = (
                int(store.get("v4_dir", 0))
                if state.timestamp <= int(store.get("v4_dir_til", -1))
                else 0
            )
            return v_active, vev_dir, basket_active, v4_dir

        def implied_spot_tilt(self, state: TradingState, store: Dict, velvet_mid: float) -> float:
            weighted = total_w = 0.0
            for strike in (5100, 5200):
                opt_q = quote_from(state.order_depths.get(f"VEV_{strike}"))
                if opt_q.mid is None or opt_q.spread is None or opt_q.spread > 3:
                    continue
                iv_obs = implied_vol(velvet_mid, strike, TTE, opt_q.mid)
                iv_smooth = update_ema(store["emas"], f"iv_for_implied_{strike}", iv_obs, 60)

                lo, hi = velvet_mid - 50.0, velvet_mid + 50.0
                for _ in range(20):
                    mid = 0.5 * (lo + hi)
                    if bs_call(mid, strike, TTE, iv_smooth) > opt_q.mid:
                        hi = mid
                    else:
                        lo = mid
                implied_s = 0.5 * (lo + hi)
                weight = 1.0 / max(1, opt_q.spread)
                weighted += weight * (implied_s - velvet_mid)
                total_w += weight

            if total_w == 0:
                return 0.0
            raw = weighted / total_w
            smooth = update_ema(store["emas"], "implied_spot_dev", raw, 60)
            return max(-0.5, min(0.5, 0.4 * (raw - smooth)))

        # ---- HYDROGEL_PACK: historical-fair adaptive mean reversion ----
        def trade_hydro(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
        ) -> None:
            q = quote_from(state.order_depths.get(HYDRO))
            wall = q.wall_mid
            if q.bid is None or q.ask is None or wall is None:
                return
            orders = result.setdefault(HYDRO, [])
            position = self.position(state, HYDRO)

            # Historical center across data/ROUND_3 is ~9991. The submission
            # logs sat a bit lower, but 9988 worsened public total and min-day,
            # so this general variant gives historical data the main vote.
            fast = update_ema(store["emas"], f"{HYDRO}_fast", wall, 30)
            slow = update_ema(store["emas"], f"{HYDRO}_slow", wall, 120)
            fair = 0.20 * wall + 0.25 * fast + 0.40 * slow + 0.15 * 9991.0
            fair -= 0.05 * position

            TAKE_EDGE = 7.0
            QUOTE_EDGE = 4.0
            QUOTE_SIZE = 18

            if q.ask is not None and q.ask <= fair - TAKE_EDGE:
                self.buy(state, HYDRO, orders, q.ask, min(-q.ask_vol, 35))
            if q.bid is not None and q.bid >= fair + TAKE_EDGE:
                self.sell(state, HYDRO, orders, q.bid, min(q.bid_vol, 35))

            if q.spread is not None and q.spread >= 10:
                target_bid = int(min(q.bid + 1, math.floor(fair - QUOTE_EDGE)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + QUOTE_EDGE)))
                if target_bid < target_ask:
                    self.buy(state, HYDRO, orders, target_bid, QUOTE_SIZE)
                    self.sell(state, HYDRO, orders, target_ask, QUOTE_SIZE)

        # ---- VELVETFRUIT_EXTRACT (smile_surface): EMA + insider tilt + saturated MM
        # Uses wall_mid (more stable than raw mid) as the EMA source, per hedgehogs.
        # Note: vev_dir is intentionally NOT used here. It hurts VELVET (-$60K vs
        # winner) while helping VEV_5300 — consumed only in trade_5300.
        def trade_velvet(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
            v_active: bool,
            implied_tilt: float,
            v4_dir: int,
        ) -> None:
            q = quote_from(state.order_depths.get(VELVET))
            wall = q.wall_mid
            if wall is None:
                return
            orders = result.setdefault(VELVET, [])
            position = self.position(state, VELVET)
            fast = update_ema(store["emas"], f"{VELVET}_fast", wall, 15)

            # 5255 is not from a single submission log: it is the day-2
            # historical center and wins all public days in rank.
            fair = 0.7 * fast + 0.3 * 5255.0
            fair -= 0.005 * position
            if v_active:
                fair += 1.5
            fair += implied_tilt
            fair += 1.0 * v4_dir

            if v_active and q.ask is not None and q.ask <= fair:
                self.buy(state, VELVET, orders, q.ask, min(-q.ask_vol, 25))

            # Saturated MM (no cross-book guard — matches the winner)
            target_bid = int(math.floor(fair - 2.0))
            target_ask = int(math.ceil(fair + 2.0))
            self.buy(state, VELVET, orders, target_bid, POS_LIMITS[VELVET])
            self.sell(state, VELVET, orders, target_ask, POS_LIMITS[VELVET])

        def velvet_spot_edge(
            self,
            state: TradingState,
            store: Dict,
            S: float,
            v_active: bool,
            implied_tilt: float,
            v4_dir: int,
        ) -> float:
            """The same underlying fair used by VELVET, exposed to ATM options."""
            fast = float(store["emas"].get(f"{VELVET}_fast", S))
            fair = 0.7 * fast + 0.3 * 5255.0
            fair -= 0.005 * self.position(state, VELVET)
            if v_active:
                fair += 1.5
            fair += implied_tilt
            fair += 1.0 * v4_dir
            edge = fair - S
            return max(-5.0, min(5.0, edge))

        def option_micro_reversion(
            self,
            store: Dict,
            product: str,
            q: Quote,
            S: float,
            delta: float,
            strength: float,
        ) -> float:
            """Fade one-tick option quote jumps after removing delta*S movement."""
            prev_s = store.get("prev_S")
            prev_mid = store.get("prev_mids", {}).get(product)
            if prev_s is None or prev_mid is None or q.mid is None:
                return 0.0
            residual_move = (q.mid - float(prev_mid)) - delta * (S - float(prev_s))
            if abs(residual_move) < 0.75:
                return 0.0
            return max(-2.0, min(2.0, -strength * residual_move))

        # ---- VEV_4000 / VEV_4500: flash-arb deep ITM (smile_surface) ----
        def trade_itm_flash(
            self,
            state: TradingState,
            result: Dict[str, List[Order]],
            product: str,
            strike: int,
            S: float,
            surface_shift: Optional[float],
            wing_signal: bool,
        ) -> None:
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            fair = max(S - strike, 0.0)
            spread = q.spread
            local_shift = q.mid - fair
            shift = surface_shift if surface_shift is not None else local_shift

            flash_down = shift <= -4.0
            flash_up = shift >= 4.0
            actual_cheap = q.ask <= fair - 2
            spike_bid = flash_up and q.bid >= fair + 1.0

            if flash_down and q.ask <= fair:
                size = 12 if strike == 4000 else 8
                if actual_cheap:
                    size += 4
                if wing_signal or spread <= 10:
                    size += 3
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))

            if actual_cheap:
                size = 16 if strike == 4000 else 10
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))

            if spike_bid:
                self.sell(state, product, orders, q.bid, q.bid_vol)

            if position > 0:
                if not spike_bid and (q.bid >= fair + 1 or (flash_up and q.bid >= fair)):
                    size = 10 if strike == 4000 else 7
                    self.sell(state, product, orders, q.bid,
                              min(position, q.bid_vol, size))
                target_ask = int(max(q.ask - 1, math.ceil(fair + 1.0)))
                if target_ask > q.bid:
                    self.sell(state, product, orders, target_ask, min(position, 5))

            if position <= 0 and spread >= 8 and not flash_up:
                target_bid = int(min(q.bid + 1,
                                     math.floor(fair - (2.0 if strike == 4000 else 3.0))))
                if 0 < target_bid < q.ask:
                    self.buy(state, product, orders, target_bid, 3 if strike == 4000 else 2)

        # ---- VEV_5000 / 5100 / 5200: spot-anchored ATM option strategies ----
        # The smile fit was tuned against raw mid: switching it to wall_mid
        # subtly shifts implied vols and bleeds PnL. Keep raw mid here.
        def smile_level(self, state: TradingState, store: Dict, S: float) -> float:
            weighted = total_w = 0.0
            for strike in (5000, 5100, 5200, 5300, 5400, 5500):
                q = quote_from(state.order_depths.get(f"VEV_{strike}"))
                if q.mid is None or q.spread is None:
                    continue
                iv_obs = implied_vol(S, strike, TTE, q.mid)
                iv_smooth = update_ema(store["emas"], f"iv_{strike}", iv_obs, 60)
                level = iv_smooth - smile_offset((strike - S) / 100.0)
                w = 1.0 / max(1, q.spread)
                weighted += w * level
                total_w += w
            if total_w == 0:
                return update_ema(store["emas"], "smile_level_default", 0.033, 60)
            level = update_ema(store["emas"], "smile_level", weighted / total_w, 60)
            return max(0.026, min(0.037, level))

        def trade_5000(self, state, store, result, S, spot_edge: float):
            product, strike, anchor = "VEV_5000", 5000, 13.0
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            intrinsic = max(S - strike, 0.0)
            observed_ext = q.mid - intrinsic
            ext_ema = update_ema(store["emas"], f"{product}_ext", observed_ext, 80)
            ext_blend = max(anchor - 6.0, min(anchor + 6.0, 0.5 * ext_ema + 0.5 * anchor))
            fair = intrinsic + ext_blend + 0.9 * spot_edge - 0.025 * position
            fair += self.option_micro_reversion(store, product, q, S, 0.9, 1.2)

            if q.ask <= fair - 2.5:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 12))
            if q.bid >= fair + 2.5:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, 12))

            if q.spread >= 3:
                target_bid = int(min(q.bid + 1, math.floor(fair - 1.5)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + 1.5)))
                if target_bid < target_ask:
                    if target_bid > 0 and spot_edge >= -1.5:
                        self.buy(state, product, orders, target_bid, 8)
                    if spot_edge <= 1.5:
                        self.sell(state, product, orders, target_ask, 8)

        def trade_smile_atm(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
            smile_lv: float,
            product: str,
            strike: int,
            S: float,
            v_active: bool,
            spot_edge: float,
        ) -> None:
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)
            spread = q.spread

            moneyness = (strike - S) / 100.0
            fair_iv = max(IV_LO, min(IV_HI, smile_lv + smile_offset(moneyness)))
            delta = bs_delta(S, strike, TTE, fair_iv)
            fair = bs_call(S, strike, TTE, fair_iv)
            spot_weight = 1.0 if strike == 5100 else 0.25
            fair += spot_weight * delta * spot_edge
            fair += self.option_micro_reversion(store, product, q, S, delta, 0.75)
            fair -= (0.03 if strike <= 5100 else 0.025) * position

            if strike == 5100:
                take_edge = 1.5 if spread >= 2 else 1.0
                quote_edge = 0.8 if spread >= 4 else 0.5
                size = 6
            else:
                take_edge = 1.2 if spread >= 2 else 0.8
                quote_edge = 0.7 if spread >= 4 else 0.5
                size = 6

            if q.ask <= fair - take_edge:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size * 2))
            if q.bid >= fair + take_edge:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, size * 2))

            if spread >= 2:
                target_bid = int(min(q.bid + 1, math.floor(fair - quote_edge)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + quote_edge)))
                if target_bid < target_ask:
                    if spot_edge >= (-1.25 if strike == 5100 else -2.5):
                        self.buy(state, product, orders, target_bid, size)
                    if spot_edge <= (1.25 if strike == 5100 else 2.5):
                        self.sell(state, product, orders, target_ask, size)

        # ---- VEV_5300: extrinsic + filtered vev_dir tilt (bygpt_overfit) ----
        def trade_5300(self, state, result, S, vev_dir):
            product, strike = "VEV_5300", 5300
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            fair = max(S - strike, 0.0) + 47.0
            fair -= 0.015 * position
            if vev_dir != 0:
                fair += 2.0 * vev_dir

            if q.ask < fair - 2.0:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 20))
            if q.bid > fair + 2.0:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, 20))

            if q.spread >= 2:
                target_bid = int(min(q.bid + 1, math.floor(fair - 1.0)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + 1.0)))
                if target_bid < target_ask:
                    self.buy(state, product, orders, target_bid, 5)
                    self.sell(state, product, orders, target_ask, 5)

        # ---- VEV_5400: extrinsic = 16 OTM MM (trader_strats, no take-size cap) ----
        def trade_5400(self, state, store, result, S):
            product, strike = "VEV_5400", 5400
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            fair = max(S - strike, 0.0) + 16.0
            fair += self.option_micro_reversion(store, product, q, S, 0.20, 0.60)
            fair -= 0.02 * position

            # Take entire available top-of-book volume (matching trader_strats).
            if q.ask < fair - 2.0:
                self.buy(state, product, orders, q.ask, -q.ask_vol)
            if q.bid > fair + 2.0:
                self.sell(state, product, orders, q.bid, q.bid_vol)

            if q.spread >= 2:
                target_bid = int(min(q.bid + 1, math.floor(fair - 1.5)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + 1.5)))
                if target_bid < target_ask:
                    self.buy(state, product, orders, target_bid, 5)
                    self.sell(state, product, orders, target_ask, 5)

        # ---- VEV_5500: basket-seller absorber plus fair-value unwind ----
        def trade_5500(self, state, store, result, S, basket_active: bool):
            product, strike = "VEV_5500", 5500
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            intrinsic = max(S - strike, 0.0)
            anchor = 6.5
            observed_ext = q.mid - intrinsic
            ext_ema = update_ema(store["emas"], f"{product}_ext", observed_ext, 120)
            ext_blend = max(anchor - 3.5, min(anchor + 3.5, 0.35 * ext_ema + 0.65 * anchor))
            fair = intrinsic + ext_blend
            fair += self.option_micro_reversion(store, product, q, S, 0.08, 0.50)

            if basket_active and q.ask <= fair - 0.5:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 8))
            elif q.ask <= fair - 2.5:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 5))
            if q.bid >= fair + 2.5:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, 5))

            if q.spread is not None and q.spread <= 2 and q.bid <= fair - 0.5:
                size = 7 if basket_active else 3
                target_bid = q.bid
                if q.spread >= 2 and q.bid + 1 < q.ask:
                    target_bid = q.bid + 1
                self.buy(state, product, orders, target_bid, size)

            if position > 0:
                target_ask = int(max(q.ask, math.ceil(fair + 1.0)))
                if target_ask > q.bid:
                    self.sell(state, product, orders, target_ask, min(position, 5))
            elif position < 0:
                target_bid = int(min(q.bid, math.floor(fair - 1.0)))
                if 0 < target_bid < q.ask:
                    self.buy(state, product, orders, target_bid, min(-position, 5))

        # ---- VEV_6000 / VEV_6500: absorb zero-priced basket legs ----
        def trade_zero_tail(self, state, result, product, basket_active: bool):
            q = quote_from(state.order_depths.get(product))
            if q.bid is None or q.ask is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            if q.bid == 0:
                size = POS_LIMITS[product] if basket_active else 40
                self.buy(state, product, orders, 0, size)

            if position > 0 and q.ask >= 1:
                self.sell(state, product, orders, 1, min(position, 20))

        # ---- main ----
        def run(self, state: TradingState):
            result: Dict[str, List[Order]] = {}
            store = self.load_state(state.traderData)
            total_pnl = self.mark_pnl(state, store)
            v_active, vev_dir, basket_active, v4_dir = self.update_signals(state, store)

            velvet_q = quote_from(state.order_depths.get(VELVET))
            S = velvet_q.mid
            implied_tilt = self.implied_spot_tilt(state, store, S) if S is not None else 0.0

            self.trade_hydro(state, store, result)
            self.trade_velvet(state, store, result, v_active, implied_tilt, v4_dir)

            # The flash-arb / smile-surface strategies were tuned to raw mid;
            # only the VELVET MM benefits from wall_mid (already used inside
            # trade_velvet). Use raw mid for everything downstream.
            if S is None:
                result = {p: o for p, o in result.items() if o}
                return result, 0, jsonpickle.encode(store)

            spot_edge = self.velvet_spot_edge(state, store, S, v_active, implied_tilt, v4_dir)
            smile_lv = self.smile_level(state, store, S)
            self.update_low_iv_trail(store, total_pnl, smile_lv)

            if store.get("option_risk_off"):
                self.flatten_options(state, result)
                store["prev_S"] = S
                prev_mids = store.setdefault("prev_mids", {})
                for product in (
                    "VEV_4000", "VEV_4500", "VEV_5000", "VEV_5100", "VEV_5200",
                    "VEV_5300", "VEV_5400", "VEV_5500",
                ):
                    mid = quote_from(state.order_depths.get(product)).mid
                    if mid is not None:
                        prev_mids[product] = mid
                result = {p: o for p, o in result.items() if o}
                return result, 0, jsonpickle.encode(store)

            # Surface shift across deep-ITM strikes (flash-bug detector).
            shifts = []
            for p, k in (("VEV_4000", 4000), ("VEV_4500", 4500)):
                opt_mid = quote_from(state.order_depths.get(p)).mid
                if opt_mid is not None:
                    shifts.append(opt_mid - max(S - k, 0.0))
            surface_shift = sum(shifts) / len(shifts) if shifts else None

            wing_signal = basket_active or any(
                state.market_trades.get(p)
                for p in ("VEV_5300", "VEV_5400", "VEV_5500", "VEV_6000", "VEV_6500")
            )

            self.trade_itm_flash(state, result, "VEV_4000", 4000, S, surface_shift, wing_signal)
            self.trade_itm_flash(state, result, "VEV_4500", 4500, S, surface_shift, wing_signal)

            self.trade_5000(state, store, result, S, spot_edge)
            self.trade_smile_atm(state, store, result, smile_lv, "VEV_5100", 5100, S, v_active, spot_edge)
            self.trade_smile_atm(state, store, result, smile_lv, "VEV_5200", 5200, S, v_active, spot_edge)

            self.trade_5300(state, result, S, vev_dir)
            self.trade_5400(state, store, result, S)
            self.trade_5500(state, store, result, S, basket_active)
            self.trade_zero_tail(state, result, "VEV_6000", basket_active)
            self.trade_zero_tail(state, result, "VEV_6500", basket_active)

            store["prev_S"] = S
            prev_mids = store.setdefault("prev_mids", {})
            for product in (
                "VEV_4000", "VEV_4500", "VEV_5000", "VEV_5100", "VEV_5200",
                "VEV_5300", "VEV_5400", "VEV_5500",
            ):
                mid = quote_from(state.order_depths.get(product)).mid
                if mid is not None:
                    prev_mids[product] = mid

            result = {p: o for p, o in result.items() if o}
            return result, 0, jsonpickle.encode(store)

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

trader_FLIPVOL = __build_trader_FLIPVOL()
traders.ROUND_3.trader_FLIPVOL = trader_FLIPVOL
# --- end pasted traders/ROUND_3/trader_FLIPVOL.py ---

# --- begin pasted traders/ROUND_3/trader_DELTABEAST.py ---
def __build_trader_DELTABEAST():
    """ROUND_3 experiment: stack VELVET mean-reversion into delta vouchers.

    This is intentionally thin: it reuses trader_FLIPVOL and only changes the
    missing class of edge suggested by the high-PnL target, namely using
    VEV_4000..5200 as additional delta capacity for the underlying signal.
    """

    import math
    from typing import Dict, List, Optional

    from datamodel import Order, TradingState

    base = globals()['trader_FLIPVOL']


    class Trader(base.Trader):
        def update_low_iv_trail(self, store: Dict, total_pnl: float, smile_lv: float) -> None:
            # Public target keeps harvesting options; do not switch into the
            # conservative day-3 risk-off mode while hunting this edge.
            return

        def velvet_spot_edge(
            self,
            state: TradingState,
            store: Dict,
            S: float,
            v_active: bool,
            implied_tilt: float,
            v4_dir: int,
        ) -> float:
            fast = float(store["emas"].get(f"{base.VELVET}_fast", S))
            fair = 0.7 * fast + 0.3 * 5255.0
            fair -= 0.002 * self.position(state, base.VELVET)
            if v_active:
                fair += 1.5
            fair += implied_tilt
            fair += 1.0 * v4_dir
            edge = max(-18.0, min(18.0, fair - S))
            self._spot_edge = edge
            return edge

        def trade_itm_flash(
            self,
            state: TradingState,
            result: Dict[str, List[Order]],
            product: str,
            strike: int,
            S: float,
            surface_shift: Optional[float],
            wing_signal: bool,
        ) -> None:
            super().trade_itm_flash(state, result, product, strike, S, surface_shift, wing_signal)

            q = base.quote_from(state.order_depths.get(product))
            if q.mid is None or q.bid is None or q.ask is None or q.spread is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)
            spot_edge = float(getattr(self, "_spot_edge", 0.0))
            if abs(spot_edge) < 1.25:
                return

            # Deep ITM vouchers are almost delta-one VELVET with a wider book.
            # Quote only when the underlying signal is strong enough to pay toll.
            fair = max(S - strike, 0.0) + spot_edge - 0.006 * position
            take_edge = 3.0 if strike == 4000 else 2.5
            quote_edge = 2.0 if strike == 4000 else 1.5
            size = 18 if strike == 4000 else 16

            if q.ask <= fair - take_edge:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))
            if q.bid >= fair + take_edge:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, size))

            if q.spread >= 5:
                target_bid = int(min(q.bid + 1, math.floor(fair - quote_edge)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + quote_edge)))
                if target_bid < target_ask:
                    if spot_edge > -4.0:
                        self.buy(state, product, orders, target_bid, 10)
                    if spot_edge < 4.0:
                        self.sell(state, product, orders, target_ask, 10)

        def trade_5000(self, state, store, result, S, spot_edge: float):
            product, strike, anchor = "VEV_5000", 5000, 13.0
            q = base.quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            intrinsic = max(S - strike, 0.0)
            observed_ext = q.mid - intrinsic
            ext_ema = base.update_ema(store["emas"], f"{product}_ext", observed_ext, 80)
            ext_blend = max(anchor - 6.0, min(anchor + 6.0, 0.5 * ext_ema + 0.5 * anchor))
            fair = intrinsic + ext_blend + 1.05 * spot_edge - 0.008 * position
            fair += self.option_micro_reversion(store, product, q, S, 0.92, 1.0)

            if q.ask <= fair - 1.6:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 18))
            if q.bid >= fair + 1.6:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, 18))

            if q.spread >= 3:
                target_bid = int(min(q.bid + 1, math.floor(fair - 0.8)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + 0.8)))
                if target_bid < target_ask:
                    if spot_edge >= -4.0:
                        self.buy(state, product, orders, target_bid, 12)
                    if spot_edge <= 4.0:
                        self.sell(state, product, orders, target_ask, 12)

        def trade_smile_atm(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
            smile_lv: float,
            product: str,
            strike: int,
            S: float,
            v_active: bool,
            spot_edge: float,
        ) -> None:
            q = base.quote_from(state.order_depths.get(product))
            if q.mid is None or q.spread is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            moneyness = (strike - S) / 100.0
            fair_iv = max(base.IV_LO, min(base.IV_HI, smile_lv + base.smile_offset(moneyness)))
            delta = base.bs_delta(S, strike, base.TTE, fair_iv)
            fair = base.bs_call(S, strike, base.TTE, fair_iv)
            # Core change: full underlying mean-reversion edge, especially 5200.
            fair += 1.25 * delta * spot_edge
            fair += self.option_micro_reversion(store, product, q, S, delta, 0.65)
            fair -= (0.010 if strike == 5100 else 0.008) * position

            take_edge = 1.2 if strike == 5100 else 1.0
            quote_edge = 0.6 if strike == 5100 else 0.5
            size = 14 if strike == 5100 else 16

            if q.ask <= fair - take_edge:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))
            if q.bid >= fair + take_edge:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, size))

            if q.spread >= 2:
                target_bid = int(min(q.bid + 1, math.floor(fair - quote_edge)))
                target_ask = int(max(q.ask - 1, math.ceil(fair + quote_edge)))
                if target_bid < target_ask:
                    if spot_edge >= -4.0:
                        self.buy(state, product, orders, target_bid, size)
                    if spot_edge <= 4.0:
                        self.sell(state, product, orders, target_ask, size)

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

trader_DELTABEAST = __build_trader_DELTABEAST()
traders.ROUND_3.trader_DELTABEAST = trader_DELTABEAST
# --- end pasted traders/ROUND_3/trader_DELTABEAST.py ---

# --- begin pasted traders/ROUND_3/trader_MS.py ---
def __build_trader_MS():
    import math
    from dataclasses import dataclass
    from statistics import NormalDist
    from typing import Dict, List, Optional, Tuple

    import jsonpickle

    from datamodel import Order, TradingState


    # ── Black-Scholes (statistics.NormalDist, no scipy needed) ──────────────────

    NORMAL = NormalDist()
    TTE = 1.0
    IV_LO, IV_HI = 1e-4, 0.08


    def bs_call(S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return max(S - K, 0.0)
        sqrt_t = math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / (sigma * sqrt_t)
        d2 = d1 - sigma * sqrt_t
        return S * NORMAL.cdf(d1) - K * NORMAL.cdf(d2)


    def bs_vega(S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return 0.0
        sqrt_t = math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / (sigma * sqrt_t)
        return S * NORMAL.pdf(d1) * sqrt_t


    def bs_delta(S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return 1.0 if S > K else 0.0
        sqrt_t = math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / (sigma * sqrt_t)
        return NORMAL.cdf(d1)


    def implied_vol(S: float, K: float, T: float, market_price: float,
                    sigma_init: float = 0.03, iters: int = 30) -> float:
        if market_price <= max(S - K, 0.0) + 1e-6:
            return IV_LO
        sigma = sigma_init
        for _ in range(iters):
            diff = bs_call(S, K, T, sigma) - market_price
            if abs(diff) < 1e-6:
                break
            v = bs_vega(S, K, T, sigma)
            if v < 1e-8:
                break
            sigma = max(IV_LO, min(IV_HI, sigma - diff / v))
        return sigma


    # ── Smile shape (raw mid calibrated, kept identical to trader_final) ────────

    SMILE_KNOTS: Tuple[Tuple[float, float], ...] = (
        (-2.5, -0.0006),
        (-1.5, -0.0012),
        (-0.5, -0.0003),
        (0.5,   0.0),
        (1.5,  -0.0019),
        (2.5,   0.0005),
        (7.5,  -0.0040),
        (12.5, -0.0060),
    )


    def smile_offset(moneyness: float) -> float:
        if moneyness <= SMILE_KNOTS[0][0]:
            return SMILE_KNOTS[0][1]
        if moneyness >= SMILE_KNOTS[-1][0]:
            return SMILE_KNOTS[-1][1]
        for (x0, y0), (x1, y1) in zip(SMILE_KNOTS, SMILE_KNOTS[1:]):
            if x0 <= moneyness <= x1:
                return y0 + (y1 - y0) * (moneyness - x0) / (x1 - x0)
        return 0.0


    # ── Quote helpers ───────────────────────────────────────────────────────────


    @dataclass
    class Quote:
        bid: Optional[int] = None
        bid_vol: int = 0
        ask: Optional[int] = None
        ask_vol: int = 0
        bid_wall: Optional[int] = None
        ask_wall: Optional[int] = None

        @property
        def mid(self) -> Optional[float]:
            if self.bid is None or self.ask is None:
                return None
            return (self.bid + self.ask) / 2.0

        @property
        def wall_mid(self) -> Optional[float]:
            bw = self.bid_wall if self.bid_wall is not None else self.bid
            aw = self.ask_wall if self.ask_wall is not None else self.ask
            if bw is None or aw is None:
                return None
            return (bw + aw) / 2.0

        @property
        def spread(self) -> Optional[int]:
            if self.bid is None or self.ask is None:
                return None
            return self.ask - self.bid


    def quote_from(order_depth) -> Quote:
        q = Quote()
        if order_depth is None:
            return q
        if order_depth.buy_orders:
            q.bid = max(order_depth.buy_orders)
            q.bid_vol = order_depth.buy_orders[q.bid]
            q.bid_wall = max(order_depth.buy_orders, key=lambda p: order_depth.buy_orders[p])
        if order_depth.sell_orders:
            q.ask = min(order_depth.sell_orders)
            q.ask_vol = order_depth.sell_orders[q.ask]
            q.ask_wall = min(order_depth.sell_orders, key=lambda p: -order_depth.sell_orders[p])
        return q


    def update_ema(emas: Dict[str, float], key: str, value: float, window: int) -> float:
        if key not in emas:
            emas[key] = value
            return value
        alpha = 2.0 / (window + 1.0)
        emas[key] = alpha * value + (1.0 - alpha) * emas[key]
        return emas[key]


    # ── Per-product config ──────────────────────────────────────────────────────

    VELVET = "VELVETFRUIT_EXTRACT"
    HYDRO = "HYDROGEL_PACK"

    # Actual game limits: HYDRO/VELVET = 200, every VEV voucher = 300.
    # We use soft caps on individual options to avoid sitting on too much
    # directional gamma; the deep-ITM and ATM strikes are bumped up to
    # match where most of the working PnL came from in trader_final.
    POS_LIMITS = {
        VELVET: 200,
        HYDRO: 200,
        "VEV_4000": 290,
        "VEV_4500": 290,
        "VEV_5000": 200,
        "VEV_5100": 200,
        "VEV_5200": 290,
        "VEV_5300": 290,
        "VEV_5400": 200,
        "VEV_5500": 100,
        "VEV_6000": 80,
        "VEV_6500": 80,
    }

    # Empirical extrinsics from notebooks/round3/conclusions.ipynb (avg D0).
    # Used for ATM and wing strategies. These differ materially from the
    # placeholder anchors in trader_combined (which had 5100=8 → -$3K bleed).
    EXT_ANCHOR = {
        5000: 7.0,
        5100: 18.0,
        5200: 50.0,
        5300: 47.0,
        5400: 16.0,
        5500: 8.0,
        6000: 0.5,
        6500: 0.5,
    }


    # ── Trader ──────────────────────────────────────────────────────────────────


    class Trader:
        # ---- state ----
        def load_state(self, td: str) -> Dict:
            default = {
                "emas": {},
                "v_signal_til": -1,
                "vev_dir": 0,
                "vev_dir_til": -1,
                "wing_dump_til": -1,
                # MADSCIENTIST signals
                "basket_tilt_til": -1,        # wing-basket → ATM tilt window
                "basket_strikes": 0,           # number of strikes that fired
                "v4_buy_til": -1,              # VEV_4000 trader BUY tilt
                "v4_sell_til": -1,
            }
            if not td:
                return default
            try:
                data = jsonpickle.decode(td)
            except Exception:
                return default
            for k, v in default.items():
                data.setdefault(k, v)
            return data

        # ---- order helpers ----
        @staticmethod
        def position(state: TradingState, product: str) -> int:
            return int(state.position.get(product, 0))

        def buy_room(self, state, product, orders) -> int:
            used = sum(o.quantity for o in orders if o.quantity > 0)
            return max(0, POS_LIMITS[product] - self.position(state, product) - used)

        def sell_room(self, state, product, orders) -> int:
            used = sum(-o.quantity for o in orders if o.quantity < 0)
            return max(0, POS_LIMITS[product] + self.position(state, product) - used)

        def buy(self, state, product, orders, price, qty):
            qty = min(max(0, int(qty)), self.buy_room(state, product, orders))
            if qty > 0:
                orders.append(Order(product, int(price), qty))

        def sell(self, state, product, orders, price, qty):
            qty = min(max(0, int(qty)), self.sell_room(state, product, orders))
            if qty > 0:
                orders.append(Order(product, int(price), -qty))

        # ---- Signals ----
        def update_signals(self, state: TradingState, store: Dict) -> Tuple[bool, int, bool]:
            # Accumulator (insider) signal — ≥9 lot VELVET prints.
            for tr in state.market_trades.get(VELVET, []):
                if abs(int(tr.quantity)) >= 9:
                    store["v_signal_til"] = state.timestamp + 1500
                    break

            # Wing-seller basket detector. Two thresholds:
            #   wing_dump_til (any wing trade)            — used by 4000/4500 sizing
            #   basket_tilt_til (≥3 strikes same tick)    — used by ATM tilt
            wing_strikes_firing = sum(
                1
                for p in ("VEV_5300", "VEV_5400", "VEV_5500", "VEV_6000", "VEV_6500")
                if state.market_trades.get(p)
            )
            if wing_strikes_firing >= 1:
                store["wing_dump_til"] = state.timestamp + 200
            # Basket firing detector. ≥3 distinct strikes in same tick is
            # too strict for the simulated trade format; even single wing
            # trades correlate with +0.87 ATM drift events. But we MUST
            # debounce — refreshing the TTL every wing tick produces
            # near-permanent fair-value miscalibration that eats PnL.
            already_in_window = state.timestamp <= int(store.get("basket_tilt_til", -1))
            store["basket_just_fired"] = (wing_strikes_firing >= 1) and not already_in_window
            if store["basket_just_fired"]:
                store["basket_tilt_til"] = state.timestamp + 100
                store["basket_strikes"] = wing_strikes_firing

            # VEV_4000 trader copy: the trader signs sizes 1-3 (no other
            # taker hits VEV_4000), so we tag any 1-3 lot trade by direction.
            # 21-tick spread on 4000 means we use the wide bid/ask boundary
            # rather than mid (mid is too noisy); buy = price ≥ ask_wall.
            q4000 = quote_from(state.order_depths.get("VEV_4000"))
            for tr in state.market_trades.get("VEV_4000", []):
                n = abs(int(tr.quantity))
                if 1 <= n <= 3 and q4000.mid is not None:
                    if q4000.bid is not None and tr.price >= q4000.mid:
                        # Trade priced at/above mid — likely a BUY (lifted ask).
                        store["v4_buy_til"] = state.timestamp + 2000
                    elif tr.price < q4000.mid:
                        store["v4_sell_til"] = state.timestamp + 2000

            # vev_dir: tightness-gated directional score on 5200/5300 trades.
            q5200 = quote_from(state.order_depths.get("VEV_5200"))
            q5300 = quote_from(state.order_depths.get("VEV_5300"))
            tight = (
                q5200.spread is not None and q5200.spread <= 2
                and q5300.spread is not None and q5300.spread <= 2
            )
            if tight:
                score = 0
                for prod in ("VEV_5200", "VEV_5300"):
                    q = quote_from(state.order_depths.get(prod))
                    if q.mid is None:
                        continue
                    for tr in state.market_trades.get(prod, []):
                        px = int(tr.price)
                        n = abs(int(tr.quantity))
                        if q.ask is not None and px >= q.ask:
                            score += n
                        elif q.bid is not None and px <= q.bid:
                            score -= n
                        elif px > q.mid:
                            score += n
                        elif px < q.mid:
                            score -= n
                if score > 0:
                    store["vev_dir"] = 1
                    store["vev_dir_til"] = state.timestamp + 1200
                elif score < 0:
                    store["vev_dir"] = -1
                    store["vev_dir_til"] = state.timestamp + 1200

            v_active = state.timestamp <= int(store.get("v_signal_til", -1))
            vev_dir = (
                int(store.get("vev_dir", 0))
                if state.timestamp <= int(store.get("vev_dir_til", -1))
                else 0
            )
            wing_dump = state.timestamp <= int(store.get("wing_dump_til", -1))
            return v_active, vev_dir, wing_dump

        def basket_tilt_strength(self, state: TradingState, store: Dict) -> float:
            """[0..1] strength for the wing-basket → ATM tilt, decaying
            linearly over the 100-tick high-alpha window."""
            til = int(store.get("basket_tilt_til", -1))
            if state.timestamp > til:
                return 0.0
            remaining = til - state.timestamp
            return max(0.0, min(1.0, remaining / 100.0))

        # ---- VELVET-vs-ATM implied-spot tilt ----
        def implied_spot_tilt(
            self,
            state: TradingState,
            store: Dict,
            velvet_mid: float,
        ) -> float:
            """Return a tilt added to VELVET fair when option-side mids
            disagree with VELVET. Uses BS to invert option mids into an
            implied spot, then debiases against an EMA of the implied-spot
            deviation (so persistent biases — e.g. a stale extrinsic
            anchor — wash out).

            Uses VEV_5100 / VEV_5200 only: 5000 has too wide a spread to
            be informative, 5300+ is too low-delta. Both strikes have the
            steepest delta among quoted options so a 1-tick option move =
            ~2 ticks of implied spot move, which leads VELVET by a tick
            on micro-flow events.

            Tilt is clamped to ±0.5 — VELVET MM size means even a
            small bias produces meaningful exposure, and over-trusting
            a noisy signal would override the saturated MM.
            """
            # Pick the tighter of the two; weight by 1/spread.
            weighted = total_w = 0.0
            for strike in (5100, 5200):
                opt_q = quote_from(state.order_depths.get(f"VEV_{strike}"))
                if opt_q.mid is None or opt_q.spread is None or opt_q.spread > 3:
                    continue
                iv_obs = implied_vol(velvet_mid, strike, TTE, opt_q.mid)
                iv_smooth = update_ema(
                    store["emas"], f"iv_for_implied_{strike}", iv_obs, 60
                )
                # Implied spot from inverting BS on a smoothed IV — solve
                # bs_call(S_imp, K, T, iv) = opt_mid via a tight bisection.
                lo, hi = velvet_mid - 50, velvet_mid + 50
                for _ in range(20):
                    mid = 0.5 * (lo + hi)
                    if bs_call(mid, strike, TTE, iv_smooth) > opt_q.mid:
                        hi = mid
                    else:
                        lo = mid
                implied_s = 0.5 * (lo + hi)
                w = 1.0 / max(1, opt_q.spread)
                weighted += w * (implied_s - velvet_mid)
                total_w += w

            if total_w == 0:
                return 0.0
            raw = weighted / total_w
            smooth = update_ema(store["emas"], "implied_spot_dev", raw, 60)
            # Subtract the EMA-baseline so a *change* in implied disagreement
            # is what we trade, not a persistent miscalibration.
            signal = raw - smooth
            return max(-0.5, min(0.5, 0.4 * signal))

        # ---- HYDROGEL_PACK (claude_carry_2 fair, trader_final execution) ----
        # claude_carry_2 corrects anchor from 9991 → 9980 (closer to the
        # observed regime mean) and bumps position skew to 0.06. We keep
        # those changes but use trader_final's wall_mid input + tighter
        # quote_edge=4 + larger take_size=35 because those execution knobs
        # outperform claude_carry_2's mid/edge=5/take=28 on this dataset.
        def trade_hydro(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
        ) -> None:
            depth = state.order_depths.get(HYDRO)
            if depth is None:
                return
            q = quote_from(depth)
            wall = q.wall_mid
            if q.bid is None or q.ask is None or wall is None:
                return
            orders = result.setdefault(HYDRO, [])
            position = self.position(state, HYDRO)

            # MADSCIENTIST: anchor = 9988 (trader_final used 9991 / $97K,
            # claude_carry_2 used 9980 / $88K — split the difference).
            ANCHOR = 9991.0
            FAST_W, SLOW_W = 30, 120
            TAKE_EDGE = 7.0
            QUOTE_EDGE = 4.0
            QUOTE_SIZE = 18
            MIN_SPREAD = 10
            SKEW = 0.005  # MADSCIENTIST: ultra-soft (best of grid)

            fast = update_ema(store["emas"], f"{HYDRO}_fast", wall, FAST_W)
            slow = update_ema(store["emas"], f"{HYDRO}_slow", wall, SLOW_W)
            fair = 0.20 * wall + 0.25 * fast + 0.40 * slow + 0.15 * ANCHOR
            fair -= SKEW * position

            if q.ask <= fair - TAKE_EDGE:
                self.buy(state, HYDRO, orders, q.ask, min(-q.ask_vol, 35))
            if q.bid >= fair + TAKE_EDGE:
                self.sell(state, HYDRO, orders, q.bid, min(q.bid_vol, 35))

            if q.spread >= MIN_SPREAD:
                tb = int(min(q.bid + 1, math.floor(fair - QUOTE_EDGE)))
                ta = int(max(q.ask - 1, math.ceil(fair + QUOTE_EDGE)))
                if tb < ta:
                    self.buy(state, HYDRO, orders, tb, QUOTE_SIZE)
                    self.sell(state, HYDRO, orders, ta, QUOTE_SIZE)

        # ---- VELVETFRUIT_EXTRACT (OPTIMUM + VEV_4000-trader copy tilt) ----
        def trade_velvet(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
            v_active: bool,
            implied_tilt: float,
        ) -> None:
            q = quote_from(state.order_depths.get(VELVET))
            wall = q.wall_mid
            if wall is None:
                return
            orders = result.setdefault(VELVET, [])
            position = self.position(state, VELVET)
            fast = update_ema(store["emas"], f"{VELVET}_fast", wall, 15)

            fair = 0.7 * fast + 0.3 * 5255.0
            # MADSCIENTIST: softer skew
            fair -= 0.005 * position
            if v_active:
                fair += 1.5
            fair += implied_tilt

            # MADSCIENTIST(C): VEV_4000-trader copy. Their BUY prints predict
            # +0.41 tick VELVET drift at 1k. Translate to a small fair tilt
            # whenever the v4 trader is "active". Capped because hit rate
            # is only 53-56% and there are only ~155 events/day.
            v4_buy_active = state.timestamp <= int(store.get("v4_buy_til", -1))
            v4_sell_active = state.timestamp <= int(store.get("v4_sell_til", -1))
            if v4_buy_active and not v4_sell_active:
                fair += 1.0
            elif v4_sell_active and not v4_buy_active:
                fair -= 1.0

            if v_active and q.ask is not None and q.ask <= fair:
                self.buy(state, VELVET, orders, q.ask, min(-q.ask_vol, 25))

            target_bid = int(math.floor(fair - 2.0))
            target_ask = int(math.ceil(fair + 2.0))
            self.buy(state, VELVET, orders, target_bid, POS_LIMITS[VELVET])
            self.sell(state, VELVET, orders, target_ask, POS_LIMITS[VELVET])

        # ---- VEV_4000 / VEV_4500: flash-arb deep ITM (unchanged) ----
        def trade_itm_flash(
            self,
            state: TradingState,
            result: Dict[str, List[Order]],
            product: str,
            strike: int,
            S: float,
            surface_shift: Optional[float],
            wing_signal: bool,
        ) -> None:
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            fair = max(S - strike, 0.0)
            spread = q.spread
            local_shift = q.mid - fair
            shift = surface_shift if surface_shift is not None else local_shift

            flash_down = shift <= -4.0
            flash_up = shift >= 4.0
            actual_cheap = q.ask <= fair - 2

            # MADSCIENTIST: flash-arb sizes scaled up for the 290-limit caps.
            if flash_down and q.ask <= fair:
                size = 25 if strike == 4000 else 18
                if actual_cheap:
                    size += 8
                if wing_signal or spread <= 10:
                    size += 6
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))

            if actual_cheap:
                size = 30 if strike == 4000 else 22
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))

            if position > 0:
                if q.bid >= fair + 1 or (flash_up and q.bid >= fair):
                    size = 20 if strike == 4000 else 14
                    self.sell(state, product, orders, q.bid,
                              min(position, q.bid_vol, size))
                target_ask = int(max(q.ask - 1, math.ceil(fair + 1.0)))
                if target_ask > q.bid:
                    self.sell(state, product, orders, target_ask, min(position, 10))

            if position <= 0 and spread >= 8 and not flash_up:
                target_bid = int(min(q.bid + 1,
                                     math.floor(fair - (2.0 if strike == 4000 else 3.0))))
                if 0 < target_bid < q.ask:
                    self.buy(state, product, orders, target_bid, 6 if strike == 4000 else 4)

        # ---- VEV_5000: trader_combined ATM extrinsic-anchor MM ----
        # trader_final uses anchor=13 here and made $1718. The notebook says
        # avg D0 extrinsic is 6.75; the trader_final value of 13 is what
        # actually scored — the EMA blend is letting it adapt either way.
        # Keep trader_final's params verbatim — they're the highest-PnL
        # config across the rank table for this strike.
        def trade_5000(self, state, store, result, S):
            product, strike, anchor = "VEV_5000", 5000, 13.0
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            intrinsic = max(S - strike, 0.0)
            observed_ext = q.mid - intrinsic
            ext_ema = update_ema(store["emas"], f"{product}_ext", observed_ext, 80)
            ext_blend = max(anchor - 6.0, min(anchor + 6.0, 0.5 * ext_ema + 0.5 * anchor))
            fair = intrinsic + ext_blend - 0.025 * position  # MADSCIENTIST softer

            if q.ask <= fair - 3.0:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 8))
            if q.bid >= fair + 3.0:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, 8))

            if q.spread >= 3:
                tb = int(min(q.bid + 1, math.floor(fair - 1.5)))
                ta = int(max(q.ask - 1, math.ceil(fair + 1.5)))
                if tb < ta:
                    if tb > 0:
                        self.buy(state, product, orders, tb, 5)
                    self.sell(state, product, orders, ta, 5)

        # ---- VEV_5100 / 5200: BS-smile MM (looser than trader_final) ----
        # trader_final's smile MM only fired ~17/32 trades because take_edge
        # was 1.5 on a 3-tick book. The fix isn't a different model — BS+smile
        # already correctly tracks moneyness. We just need to actually quote.
        # Lower take_edge to 0.8 / quote_edge to 0.5 and double size. Keep
        # the spread-weighted smile_lv from trader_final (works as designed).
        def trade_smile_atm(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
            smile_lv: float,
            product: str,
            strike: int,
            S: float,
            v_active: bool,
            basket_tilt: float = 0.0,
        ) -> None:
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)
            spread = q.spread

            moneyness = (strike - S) / 100.0
            fair_iv = max(IV_LO, min(IV_HI, smile_lv + smile_offset(moneyness)))
            fair = bs_call(S, strike, TTE, fair_iv)
            if v_active:
                fair += 0.8 * bs_delta(S, strike, TTE, fair_iv)
            # MADSCIENTIST(A): wing-basket tilt — empirical drifts.
            tilt_peak = {5100: 0.5, 5200: 0.87}.get(strike, 0.0)
            fair += basket_tilt * tilt_peak
            # MADSCIENTIST: softer skew (0.03 vs 0.05/0.06) — same logic
            # as 5300/5400, the 200-cap means our position can swing far
            # and aggressive skew cuts our quotes below market willingness.
            fair -= 0.03 * position

            # 5100 sits 1 strike ITM with a thin ~3-tick book — too aggressive
            # an edge gets us bagholding in regime shifts. 5200 has a wider
            # book and benefits from looser take. Per-strike tuning beats
            # uniform: trader_final used 1.5 / 0.8 uniformly and barely
            # traded 5100. We hold 5100 at trader_final's edges and ease 5200.
            if strike == 5100:
                take_edge = 1.5 if spread >= 2 else 1.0
                quote_edge = 0.8 if spread >= 4 else 0.5
                size = 6
            else:
                take_edge = 1.0 if spread >= 2 else 0.7
                quote_edge = 0.5 if spread >= 4 else 0.4
                size = 8

            if q.ask <= fair - take_edge:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size * 2))
            if q.bid >= fair + take_edge:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, size * 2))

            if spread >= 2:
                tb = int(min(q.bid + 1, math.floor(fair - quote_edge)))
                ta = int(max(q.ask - 1, math.ceil(fair + quote_edge)))
                if tb < ta:
                    self.buy(state, product, orders, tb, size)
                    self.sell(state, product, orders, ta, size)

        # ---- Smile level computation (unchanged) ----
        def smile_level(self, state: TradingState, store: Dict, S: float) -> float:
            weighted = total_w = 0.0
            for strike in (5000, 5100, 5200, 5300, 5400, 5500):
                q = quote_from(state.order_depths.get(f"VEV_{strike}"))
                if q.mid is None or q.spread is None:
                    continue
                iv_obs = implied_vol(S, strike, TTE, q.mid)
                iv_smooth = update_ema(store["emas"], f"iv_{strike}", iv_obs, 60)
                level = iv_smooth - smile_offset((strike - S) / 100.0)
                w = 1.0 / max(1, q.spread)
                weighted += w * level
                total_w += w
            if total_w == 0:
                return update_ema(store["emas"], "smile_level_default", 0.033, 60)
            level = update_ema(store["emas"], "smile_level", weighted / total_w, 60)
            return max(0.026, min(0.037, level))

        # ---- VEV_5300 (OPTIMUM + basket tilt) ----
        def trade_5300(self, state, result, S, vev_dir, basket_tilt):
            product, strike = "VEV_5300", 5300
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            fair = max(S - strike, 0.0) + 47.0
            # MADSCIENTIST: softer skew (0.03 vs OPTIMUM's 0.06) — bigger
            # 290-cap means inventory swings further; over-skewing past
            # ±150 cuts our offers below where the book pays.
            fair -= 0.03 * position
            if vev_dir != 0:
                fair += 2.0 * vev_dir
            # MADSCIENTIST(A): basket tilt — 5300 drift is +0.34 ticks.
            fair += basket_tilt * 0.34

            if q.ask < fair - 2.0:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, 10))
            if q.bid > fair + 2.0:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, 10))

            if q.spread >= 2:
                tb = int(min(q.bid + 1, math.floor(fair - 1.0)))
                ta = int(max(q.ask - 1, math.ceil(fair + 1.0)))
                if tb < ta:
                    self.buy(state, product, orders, tb, 5)
                    self.sell(state, product, orders, ta, 5)

        # ---- VEV_5400 (OPTIMUM + small basket tilt) ----
        def trade_5400(self, state, result, S, basket_tilt):
            product, strike = "VEV_5400", 5400
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            fair = max(S - strike, 0.0) + 16.0
            # MADSCIENTIST: softer skew with 200-cap.
            fair -= 0.025 * position
            # MADSCIENTIST(A): basket tilt — small 5400 drift +0.08, fades fast.
            fair += basket_tilt * 0.08

            # MADSCIENTIST: take full available size, bigger quote.
            if q.ask < fair - 2.0:
                self.buy(state, product, orders, q.ask, -q.ask_vol)
            if q.bid > fair + 2.0:
                self.sell(state, product, orders, q.bid, q.bid_vol)

            if q.spread >= 2:
                tb = int(min(q.bid + 1, math.floor(fair - 1.5)))
                ta = int(max(q.ask - 1, math.ceil(fair + 1.5)))
                if tb < ta:
                    self.buy(state, product, orders, tb, 10)
                    self.sell(state, product, orders, ta, 10)

        # ---- VEV_5500: corrected wing scalp ----
        def trade_5500(self, state, store, result, S):
            product, strike = "VEV_5500", 5500
            q = quote_from(state.order_depths.get(product))
            if q.mid is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            intrinsic = max(S - strike, 0.0)
            anchor = EXT_ANCHOR[strike]  # 8.0
            observed_ext = q.mid - intrinsic
            ext_ema = update_ema(store["emas"], f"{product}_ext", observed_ext, 100)
            ext_blend = max(anchor - 3.0, min(anchor + 3.0, 0.5 * ext_ema + 0.5 * anchor))
            fair = intrinsic + ext_blend - 0.025 * position  # MADSCIENTIST softer

            TAKE_EDGE = 2.0
            SIZE = 6

            if q.ask <= fair - TAKE_EDGE:
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, SIZE))
            if q.bid >= fair + TAKE_EDGE:
                self.sell(state, product, orders, q.bid, min(q.bid_vol, SIZE))

            if q.spread is not None and q.spread >= 2:
                tb = int(min(q.bid + 1, math.floor(fair - 1.0)))
                ta = int(max(q.ask - 1, math.ceil(fair + 1.0)))
                if tb < ta and tb > 0:
                    self.buy(state, product, orders, tb, SIZE)
                    self.sell(state, product, orders, ta, SIZE)

            # Inventory unwind (kept from trader_final for safety).
            if position > 0:
                ta = int(max(q.ask, math.ceil(fair + 1.0)))
                if ta > q.bid:
                    self.sell(state, product, orders, ta, min(position, SIZE))
            elif position < 0:
                tb = int(min(q.bid, math.floor(fair - 1.0)))
                if 0 < tb < q.ask:
                    self.buy(state, product, orders, tb, min(-position, SIZE))

        # ---- MADSCIENTIST(A2): direct take on basket fire ----
        # Bypasses fair-value rounding: lift ATM asks the moment a basket
        # event prints. The +0.87 drift on 5200 means within 100 ticks the
        # bid/ask both move up — we exit via the regular MM ask (which
        # is now also higher), capturing ~0.5-1 ticks per round trip.
        BASKET_TAKE_CFG = {
            # strike: (max_size_per_event, max_total_position_from_take)
            5200: (8, 60),
            5300: (5, 50),
        }

        def trade_basket_take(
            self, state: TradingState, store: Dict, result: Dict[str, List[Order]]
        ) -> None:
            if not store.get("basket_just_fired", False):
                return
            for strike, (size, max_pos) in self.BASKET_TAKE_CFG.items():
                product = f"VEV_{strike}"
                q = quote_from(state.order_depths.get(product))
                if q.ask is None:
                    continue
                position = self.position(state, product)
                if position >= max_pos:
                    continue
                orders = result.setdefault(product, [])
                self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))

        # ---- MADSCIENTIST(B): vertical-spread mean reversion ----
        # spread_K = mid_K - mid_{K+100} mean-reverts (diff_AR(1) ≈ -0.40).
        # Trade convergence directly via cross-leg orders. Sized small —
        # we already MM both strikes individually, so the spread trade is
        # gravy when the two-strike book gets dislocated.
        SPREAD_PAIRS = (
            # (lo_strike, hi_strike, mu, sigma, max_qty)
            (5100, 5200, 71.26, 3.62, 6),
            (5200, 5300, 48.79, 3.75, 6),
            (5300, 5400, 30.81, 3.51, 6),
        )

        def trade_vertical_spreads(
            self, state: TradingState, store: Dict, result: Dict[str, List[Order]]
        ) -> None:
            for k_lo, k_hi, mu, sigma, max_qty in self.SPREAD_PAIRS:
                sym_lo = f"VEV_{k_lo}"
                sym_hi = f"VEV_{k_hi}"
                q_lo = quote_from(state.order_depths.get(sym_lo))
                q_hi = quote_from(state.order_depths.get(sym_hi))
                if q_lo.bid is None or q_lo.ask is None or q_hi.bid is None or q_hi.ask is None:
                    continue
                orders_lo = result.setdefault(sym_lo, [])
                orders_hi = result.setdefault(sym_hi, [])

                # Cost to enter LONG spread (buy lo, sell hi) = ask_lo - bid_hi
                # Cost to enter SHORT spread (sell lo, buy hi) = -bid_lo + ask_hi
                cost_long = q_lo.ask - q_hi.bid
                cost_short = -q_lo.bid + q_hi.ask
                # Profitable LONG if cost_long < mu - threshold; the convergence
                # to mu books (mu - cost_long) per pair on average.
                threshold = 1.5 * sigma  # ~5.5 ticks at 5200-5300

                if cost_long < mu - threshold:
                    # ENTER LONG SPREAD: buy lo at ask, sell hi at bid.
                    self.buy(state, sym_lo, orders_lo, q_lo.ask,
                             min(-q_lo.ask_vol, max_qty))
                    self.sell(state, sym_hi, orders_hi, q_hi.bid,
                              min(q_hi.bid_vol, max_qty))
                elif cost_short > mu + threshold:
                    # ENTER SHORT SPREAD: sell lo at bid, buy hi at ask.
                    self.sell(state, sym_lo, orders_lo, q_lo.bid,
                              min(q_lo.bid_vol, max_qty))
                    self.buy(state, sym_hi, orders_hi, q_hi.ask,
                             min(-q_hi.ask_vol, max_qty))

        # ---- VEV_6000 / VEV_6500: free-options scoop only ----
        # These strikes are pinned at bid=0 / ask=1 / mid=0.5 forever. The
        # Wing Seller dumps the basket here, hitting the existing 0-bid.
        # We sit on the 0-bid in small size; any fill is a guaranteed
        # ≥0 EV trade because the option is floored at 0. We then offer
        # inventory back at 1 and harvest if anything lifts. We DO NOT
        # lift ask=1 — the rust backtester marks at mid=0.5 so paying 1
        # books an immediate -0.5/lot, and the wing seller almost never
        # buys back which means we'd hold the inventory all day.
        def trade_far_wing(
            self,
            state: TradingState,
            result: Dict[str, List[Order]],
            product: str,
        ) -> None:
            q = quote_from(state.order_depths.get(product))
            if q.bid is None or q.ask is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            # Offer existing inventory at the ask wall (1). Free EV: cost
            # basis is 0 from the bid scoops below.
            if position > 0:
                self.sell(state, product, orders, max(1, q.ask), min(position, 10))

            # Stack the bid wall at 0 with modest size; FIFO-ish fills come
            # from wing-seller basket dumps that hit bid=0 simultaneously.
            if q.bid == 0:
                self.buy(state, product, orders, 0, 8)

        # ---- main ----
        def run(self, state: TradingState):
            result: Dict[str, List[Order]] = {}
            store = self.load_state(state.traderData)
            v_active, vev_dir, wing_dump = self.update_signals(state, store)

            # We need VELVET mid before we can compute the ATM tilt.
            velvet_q = quote_from(state.order_depths.get(VELVET))
            S = velvet_q.mid

            if S is not None:
                implied_tilt = self.implied_spot_tilt(state, store, S)
            else:
                implied_tilt = 0.0

            self.trade_hydro(state, store, result)
            self.trade_velvet(state, store, result, v_active, implied_tilt)

            if S is None:
                result = {p: o for p, o in result.items() if o}
                return result, 0, jsonpickle.encode(store)

            # Surface shift (flash-bug detector for deep ITM).
            shifts = []
            for p, k in (("VEV_4000", 4000), ("VEV_4500", 4500)):
                opt_mid = quote_from(state.order_depths.get(p)).mid
                if opt_mid is not None:
                    shifts.append(opt_mid - max(S - k, 0.0))
            surface_shift = sum(shifts) / len(shifts) if shifts else None

            # Wing signal also folds in the persistent wing_dump TTL —
            # gives us a longer window after a basket print to size up.
            wing_signal = wing_dump or any(
                state.market_trades.get(p)
                for p in ("VEV_5300", "VEV_5400", "VEV_5500", "VEV_6000", "VEV_6500")
            )

            self.trade_itm_flash(state, result, "VEV_4000", 4000, S, surface_shift, wing_signal)
            self.trade_itm_flash(state, result, "VEV_4500", 4500, S, surface_shift, wing_signal)

            # MADSCIENTIST(A): wing-basket tilt strength
            basket_tilt = self.basket_tilt_strength(state, store)

            smile_lv = self.smile_level(state, store, S)
            self.trade_5000(state, store, result, S)
            self.trade_smile_atm(state, store, result, smile_lv, "VEV_5100", 5100, S, v_active, basket_tilt)
            self.trade_smile_atm(state, store, result, smile_lv, "VEV_5200", 5200, S, v_active, basket_tilt)

            self.trade_5300(state, result, S, vev_dir, basket_tilt)
            self.trade_5400(state, result, S, basket_tilt)
            self.trade_5500(state, store, result, S)

            # MADSCIENTIST(A2): direct take on basket events — DOESN'T WORK
            # in this engine because the spread cost (~3 ticks) exceeds the
            # capturable drift (~0.87 ticks). The MM strategy already
            # absorbs the alpha implicitly.
            # self.trade_basket_take(state, store, result)

            # MADSCIENTIST(B): vertical-spread convergence — DISABLED, eats $13K
            # self.trade_vertical_spreads(state, store, result)

            self.trade_far_wing(state, result, "VEV_6000")
            self.trade_far_wing(state, result, "VEV_6500")

            result = {p: o for p, o in result.items() if o}
            return result, 0, jsonpickle.encode(store)

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

trader_MS = __build_trader_MS()
traders.ROUND_3.trader_MS = trader_MS
# --- end pasted traders/ROUND_3/trader_MS.py ---

# --- begin pasted traders/ROUND_3/trader_SWINGBEAST.py ---
def __build_trader_SWINGBEAST():
    """ROUND_3 experiment: one-sided delta swing stack.

    Compared with DELTABEAST, this stops quoting both sides in the high-delta
    vouchers. It only adds option exposure when the underlying mean-reversion
    edge is strong enough to justify paying the option spread.
    """

    import math
    from typing import Dict, List, Optional

    from datamodel import Order, TradingState

    base = globals()['trader_FLIPVOL']
    delta = globals()['trader_DELTABEAST']


    class Trader(delta.Trader):
        def trade_itm_flash(
            self,
            state: TradingState,
            result: Dict[str, List[Order]],
            product: str,
            strike: int,
            S: float,
            surface_shift: Optional[float],
            wing_signal: bool,
        ) -> None:
            # Keep original flash-arb, not DELTABEAST's two-sided overlay.
            base.Trader.trade_itm_flash(self, state, result, product, strike, S, surface_shift, wing_signal)

            q = base.quote_from(state.order_depths.get(product))
            if q.mid is None or q.bid is None or q.ask is None or q.spread is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)
            spot_edge = float(getattr(self, "_spot_edge", 0.0))
            if abs(spot_edge) < 2.0:
                return

            fair = max(S - strike, 0.0) + spot_edge - 0.004 * position
            take_edge = 2.0 if strike == 4500 else 2.5
            quote_edge = 1.0 if strike == 4500 else 1.5
            size = 28 if strike == 4500 else 24

            if spot_edge > 0:
                if q.ask <= fair - take_edge:
                    self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))
                if q.spread >= 5:
                    bid = int(min(q.bid + 1, math.floor(fair - quote_edge)))
                    if 0 < bid < q.ask:
                        self.buy(state, product, orders, bid, size)
            else:
                if q.bid >= fair + take_edge:
                    self.sell(state, product, orders, q.bid, min(q.bid_vol, size))
                if q.spread >= 5:
                    ask = int(max(q.ask - 1, math.ceil(fair + quote_edge)))
                    if ask > q.bid:
                        self.sell(state, product, orders, ask, size)

        def trade_5000(self, state, store, result, S, spot_edge: float):
            product, strike, anchor = "VEV_5000", 5000, 13.0
            q = base.quote_from(state.order_depths.get(product))
            if q.mid is None or q.bid is None or q.ask is None or q.spread is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            intrinsic = max(S - strike, 0.0)
            observed_ext = q.mid - intrinsic
            ext_ema = base.update_ema(store["emas"], f"{product}_ext", observed_ext, 80)
            ext_blend = max(anchor - 6.0, min(anchor + 6.0, 0.5 * ext_ema + 0.5 * anchor))
            fair = intrinsic + ext_blend + 1.10 * spot_edge - 0.006 * position
            fair += self.option_micro_reversion(store, product, q, S, 0.92, 0.75)

            if spot_edge > 1.6:
                if q.ask <= fair - 1.2:
                    self.buy(state, product, orders, q.ask, min(-q.ask_vol, 26))
                if q.spread >= 3:
                    bid = int(min(q.bid + 1, math.floor(fair - 0.5)))
                    if 0 < bid < q.ask:
                        self.buy(state, product, orders, bid, 22)
            elif spot_edge < -1.6:
                if q.bid >= fair + 1.2:
                    self.sell(state, product, orders, q.bid, min(q.bid_vol, 26))
                if q.spread >= 3:
                    ask = int(max(q.ask - 1, math.ceil(fair + 0.5)))
                    if ask > q.bid:
                        self.sell(state, product, orders, ask, 22)

        def trade_smile_atm(
            self,
            state: TradingState,
            store: Dict,
            result: Dict[str, List[Order]],
            smile_lv: float,
            product: str,
            strike: int,
            S: float,
            v_active: bool,
            spot_edge: float,
        ) -> None:
            q = base.quote_from(state.order_depths.get(product))
            if q.mid is None or q.bid is None or q.ask is None or q.spread is None:
                return
            orders = result.setdefault(product, [])
            position = self.position(state, product)

            moneyness = (strike - S) / 100.0
            fair_iv = max(base.IV_LO, min(base.IV_HI, smile_lv + base.smile_offset(moneyness)))
            delta_val = base.bs_delta(S, strike, base.TTE, fair_iv)
            fair = base.bs_call(S, strike, base.TTE, fair_iv)
            mult = 1.15 if strike == 5100 else 1.45
            fair += mult * delta_val * spot_edge
            fair += self.option_micro_reversion(store, product, q, S, delta_val, 0.50)
            fair -= (0.007 if strike == 5100 else 0.005) * position

            threshold = 1.5 if strike == 5100 else 1.2
            size = 22 if strike == 5100 else 26
            if spot_edge > threshold:
                if q.ask <= fair - 0.8:
                    self.buy(state, product, orders, q.ask, min(-q.ask_vol, size))
                if q.spread >= 2:
                    bid = int(min(q.bid + 1, math.floor(fair - 0.3)))
                    if 0 < bid < q.ask:
                        self.buy(state, product, orders, bid, size)
            elif spot_edge < -threshold:
                if q.bid >= fair + 0.8:
                    self.sell(state, product, orders, q.bid, min(q.bid_vol, size))
                if q.spread >= 2:
                    ask = int(max(q.ask - 1, math.ceil(fair + 0.3)))
                    if ask > q.bid:
                        self.sell(state, product, orders, ask, size)

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

trader_SWINGBEAST = __build_trader_SWINGBEAST()
traders.ROUND_3.trader_SWINGBEAST = trader_SWINGBEAST
# --- end pasted traders/ROUND_3/trader_SWINGBEAST.py ---

# --- begin pasted traders/ROUND_4/trader_HYBRIDBEAST.py ---
def __build_trader_HYBRIDBEAST():
    """ROUND_3 experiment: per-strike hybrid of the current best beasts."""

    delta = globals()['trader_DELTABEAST']
    swing = globals()['trader_SWINGBEAST']
    ms = globals()['trader_MS']


    class Trader(delta.Trader):
        def trade_hydro(self, state, store, result):
            # Public-data monster hydro: ultra-soft skew from MADSCIENTIST.
            return ms.Trader.trade_hydro(self, state, store, result)

        def trade_itm_flash(self, state, result, product, strike, S, surface_shift, wing_signal):
            # SWING wins on the deep-ITM delta vouchers with fewer churn trades.
            return swing.Trader.trade_itm_flash(
                self, state, result, product, strike, S, surface_shift, wing_signal
            )

        def trade_5000(self, state, store, result, S, spot_edge):
            # SWING wins 5000 on every public day.
            return swing.Trader.trade_5000(self, state, store, result, S, spot_edge)

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

trader_HYBRIDBEAST = __build_trader_HYBRIDBEAST()
traders.ROUND_4.trader_HYBRIDBEAST = trader_HYBRIDBEAST
# --- end pasted traders/ROUND_4/trader_HYBRIDBEAST.py ---

Trader = trader_HYBRIDBEAST.Trader

__all__ = ['Trader']
