# Auto-generated by `uv run compile`.
# Do not edit by hand; edit the source trader and recompile.

class __CompiledModule:
    pass

traders = __CompiledModule()
traders.ROUND_5 = __CompiledModule()

# --- begin pasted traders/ROUND_5/codex_pebbles_pair_regression_mm.py ---
def __build_codex_pebbles_pair_regression_mm():
    from datamodel import OrderDepth, TradingState, Order
    from typing import Dict, List, Tuple


    class Trader:
        PAIR_MODELS: Dict[str, List[Tuple[str, float, float]]] = {
            # centered target = intercept + beta * centered reference
            "PEBBLES_S": [("PEBBLES_XL", -0.3914, 194.70), ("PEBBLES_XS", 0.4589, 123.35)],
            "PEBBLES_M": [("PEBBLES_XS", -0.3293, -591.52), ("PEBBLES_S", -0.5082, -279.36)],
            "PEBBLES_L": [("PEBBLES_M", 0.3035, 94.23)],
            "PEBBLES_XL": [("PEBBLES_S", -1.7788, 1326.43), ("PEBBLES_XS", -1.0143, 593.22)],
            "PEBBLES_XS": [("PEBBLES_XL", -0.6752, -417.30), ("PEBBLES_S", 1.3886, -1112.78)],
        }
        LIMIT = 120
        ORDER_SIZE = 8
        EDGE = 4.0

        def run(self, state: TradingState):
            mids = self.mids(state.order_depths)
            result: Dict[str, List[Order]] = {}

            for product, models in self.PAIR_MODELS.items():
                depth = state.order_depths.get(product)
                if depth is None or not depth.buy_orders or not depth.sell_orders:
                    continue
                fairs = []
                for reference, beta, intercept in models:
                    ref_mid = mids.get(reference)
                    if ref_mid is not None:
                        fairs.append(10000.0 + intercept + beta * (ref_mid - 10000.0))
                if not fairs:
                    continue

                fair = sum(fairs) / len(fairs)
                best_bid = max(depth.buy_orders)
                best_ask = min(depth.sell_orders)
                bid_price = best_bid + 1
                ask_price = best_ask - 1
                position = state.position.get(product, 0)
                buy_room = self.LIMIT - position
                sell_room = self.LIMIT + position
                orders: List[Order] = []

                if fair - bid_price >= self.EDGE and buy_room > 0:
                    orders.append(Order(product, bid_price, min(self.ORDER_SIZE, buy_room)))
                if ask_price - fair >= self.EDGE and sell_room > 0:
                    orders.append(Order(product, ask_price, -min(self.ORDER_SIZE, sell_room)))
                if orders:
                    result[product] = orders

            return result, 0, ""

        def mids(self, depths: Dict[str, OrderDepth]) -> Dict[str, float]:
            mids: Dict[str, float] = {}
            for product in self.PAIR_MODELS:
                depth = depths.get(product)
                if depth is not None and depth.buy_orders and depth.sell_orders:
                    mids[product] = (max(depth.buy_orders) + min(depth.sell_orders)) / 2.0
            return mids

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

codex_pebbles_pair_regression_mm = __build_codex_pebbles_pair_regression_mm()
traders.ROUND_5.codex_pebbles_pair_regression_mm = codex_pebbles_pair_regression_mm
# --- end pasted traders/ROUND_5/codex_pebbles_pair_regression_mm.py ---

Trader = codex_pebbles_pair_regression_mm.Trader

__all__ = ['Trader']
