# Auto-generated by `uv run compile`.
# Do not edit by hand; edit the source trader and recompile.

class __CompiledModule:
    pass

traders = __CompiledModule()
traders.ROUND_5 = __CompiledModule()

# --- begin pasted traders/ROUND_5/intro_max_strategy.py ---
def __build_intro_max_strategy():
    """Round 5 consolidated strategy: pair regression + cross-family log overlays,
    directional inventory carry, plus intro snack / strawberry / ROBOT Dish–iron /
    laundry-flow edges.

    Regime phases (indexed as day 2/3/4) are inferred only from relative pebble
    mid ordering — no timestamp rollover. Layers that depended on absolute price
    anchors (snack pair sums, strawberry intercept) refresh those anchors when the
    pebble regime advances. ROBOT dishes vol-gating adapts EWMA volatility to its
    baseline. ROBOT_DISHES: intro_group earns most dish PnL in the wildest regime
    (rank file ~137k on phase 4 vs ~57k/~18k earlier phases); gates match intro_group
    during quiet phases and relax slightly when shenanigans are detected —
    pebble-structure phase-day >= 4, or EWMA volatility spiking versus its baseline
    — with baseline reset when the inferred pebble regime advances."""

    from datamodel import OrderDepth, TradingState, Order
    from typing import Dict, List, Tuple
    import json
    import math


    class Trader:
        PEBBLES = ("PEBBLES_L", "PEBBLES_M", "PEBBLES_S", "PEBBLES_XL", "PEBBLES_XS")
        BASE_TARGETS = {
            "GALAXY_SOUNDS_BLACK_HOLES": 20,
            "GALAXY_SOUNDS_DARK_MATTER": 12,
            "GALAXY_SOUNDS_PLANETARY_RINGS": 16,
            "GALAXY_SOUNDS_SOLAR_FLAMES": 16,
            "GALAXY_SOUNDS_SOLAR_WINDS": 8,
            "MICROCHIP_CIRCLE": -10,
            "MICROCHIP_OVAL": -20,
            "MICROCHIP_RECTANGLE": -16,
            "MICROCHIP_SQUARE": 20,
            "MICROCHIP_TRIANGLE": -14,
            "OXYGEN_SHAKE_EVENING_BREATH": -16,
            "OXYGEN_SHAKE_GARLIC": 20,
            "PANEL_1X2": -16,
            "PANEL_1X4": -10,
            "PANEL_2X2": -12,
            "PANEL_2X4": 20,
            "PANEL_4X4": -10,
            "ROBOT_MOPPING": 18,
            "ROBOT_VACUUMING": -16,
            "SLEEP_POD_COTTON": 18,
            "SLEEP_POD_LAMB_WOOL": 12,
            "SLEEP_POD_NYLON": -8,
            "SLEEP_POD_POLYESTER": 20,
            "SLEEP_POD_SUEDE": 20,
            "TRANSLATOR_ASTRO_BLACK": -14,
            "TRANSLATOR_ECLIPSE_CHARCOAL": -8,
            "TRANSLATOR_GRAPHITE_MIST": 4,
            "TRANSLATOR_SPACE_GRAY": -16,
            "TRANSLATOR_VOID_BLUE": 18,
            "UV_VISOR_AMBER": -20,
            "UV_VISOR_MAGENTA": 18,
            "UV_VISOR_ORANGE": -4,
            "UV_VISOR_RED": 16,
            "UV_VISOR_YELLOW": 16,
        }
        INTRO_HANDLED = frozenset(
            {
                "SNACKPACK_CHOCOLATE",
                "SNACKPACK_PISTACHIO",
                "SNACKPACK_RASPBERRY",
                "SNACKPACK_STRAWBERRY",
                "SNACKPACK_VANILLA",
                "ROBOT_DISHES",
                "ROBOT_IRONING",
                "ROBOT_LAUNDRY",
            }
        )

        PAIR_MODELS: Dict[str, List[Tuple[str, float, float]]] = {
            "PEBBLES_S": [("PEBBLES_XL", -0.3914, 194.70), ("PEBBLES_XS", 0.4589, 123.35)],
            "PEBBLES_M": [("PEBBLES_XS", -0.3293, -591.52), ("PEBBLES_S", -0.5082, -279.36)],
            "PEBBLES_L": [("PEBBLES_M", 0.3035, 94.23)],
            "PEBBLES_XL": [("PEBBLES_S", -1.7788, 1326.43), ("PEBBLES_XS", -1.0143, 593.22)],
            "PEBBLES_XS": [("PEBBLES_XL", -0.6752, -417.30), ("PEBBLES_S", 1.3886, -1112.78)],
        }

        SCALE = 1.15
        CAP = 25
        MAX_ORDER_DIRECTIONAL = 10
        PAIR_LIMIT = 120
        PAIR_ORDER_SIZE = 8
        PAIR_EDGE = 4.0
        CROSS_WEIGHT = 5
        LONG_CAPS_BY_DAY = {
            2: {"PEBBLES_S": -60, "PEBBLES_XS": -120},
            3: {"PEBBLES_S": -60, "PEBBLES_XS": -120},
            4: {"PEBBLES_S": -180, "PEBBLES_XS": -240},
        }
        PEBBLES_TARGETS_BY_DAY = {
            4: {"PEBBLES_S": -180, "PEBBLES_XS": -230},
        }
        PAIR_SKIP_BY_DAY = {
            4: {"PEBBLES_S", "PEBBLES_XS"},
        }
        CROSS_OPEN_MODELS_BY_DAY: Dict[int, Dict[str, List[Tuple[str, float, float]]]] = {
            2: {
                "PEBBLES_M": [("TRANSLATOR_ECLIPSE_CHARCOAL", -0.0484, -0.588)],
                "PEBBLES_S": [("GALAXY_SOUNDS_BLACK_HOLES", 0.0090, -0.709)],
                "PEBBLES_XL": [("UV_VISOR_YELLOW", 0.0066, 1.753)],
                "PEBBLES_XS": [("OXYGEN_SHAKE_EVENING_BREATH", 0.0028, 1.031)],
            },
            3: {
                "PEBBLES_M": [("GALAXY_SOUNDS_SOLAR_WINDS", 0.0143, 1.448)],
                "PEBBLES_S": [("ROBOT_LAUNDRY", 0.0083, 0.571)],
                "PEBBLES_XL": [("MICROCHIP_CIRCLE", -0.0141, 1.053)],
                "PEBBLES_XS": [("GALAXY_SOUNDS_SOLAR_WINDS", -0.0205, -1.834)],
            },
            4: {
                "PEBBLES_M": [("SNACKPACK_RASPBERRY", -0.0120, 0.874)],
                "PEBBLES_XL": [("MICROCHIP_OVAL", -0.0045, -1.098)],
            },
        }

        LIMIT_INTRO = 250
        MAX_ORDER_INTRO = 20

        SNACK_PAIRS_KEYS = (
            ("SNACKPACK_CHOCOLATE", "SNACKPACK_VANILLA", "cv"),
            ("SNACKPACK_PISTACHIO", "SNACKPACK_RASPBERRY", "pr"),
        )
        SNACK_EDGE_SPREAD_MUL = 12.0
        SNACK_QUOTE_MUL = 16.0
        SNACK_EDGE_FLOOR = 55.0

        STRAW_BASKET_PRODUCT = "SNACKPACK_STRAWBERRY"
        STRAW_BASKET_COEFS = {
            "SNACKPACK_CHOCOLATE": -1.8195,
            "SNACKPACK_PISTACHIO": -1.0093,
            "SNACKPACK_RASPBERRY": -1.3033,
            "SNACKPACK_VANILLA": -1.6200,
        }
        STRAW_EDGE_SPREAD_MUL = 18.0
        STRAW_QUOTE_MUL = 24.0
        STRAW_EDGE_FLOOR = 90.0

        DISHES = "ROBOT_DISHES"
        DISHES_REVERSION = 0.30
        DISHES_VOL_DECAY = 0.93
        DISHES_VOL_GATE = 7.0
        DISHES_TAKE_EDGE = 5.0
        DISHES_GATE_SHEN_FACTOR = 0.78
        DISHES_VOL_BASELINE_DECAY = 0.993
        DISHES_BURST_VS_BASELINE = 2.05

        PASSIVE_QTY = 3
        PASSIVE_INVENTORY = 12
        PASSIVE_MIN_SPREAD = 2
        IRONING = "ROBOT_IRONING"
        IRONING_REVERSION = 0.15
        IRONING_SPREAD_FRAC = 0.45
        LAUNDRY = "ROBOT_LAUNDRY"
        FLOW_DECAY = 0.88
        FLOW_FADE_WEIGHT = -0.50
        FLOW_SPREAD_FRAC = 0.12
        FLOW_THRESHOLD_FLOOR = 0.45

        def run(self, state: TradingState):
            memory = self.load_state(state.traderData)
            day = int(memory.get("day", 2))
            carry_mode = bool(memory.get("carry_mode", False))
            new_day = False
            inferred_day = self.infer_day_from_pebbles_regime(state)
            if inferred_day is not None and inferred_day > day:
                new_day = True
                carry_mode = carry_mode or self.has_pebbles_inventory(state)
                day = inferred_day

            mids = self.mids(state.order_depths)
            open_mids = memory.get("open_mids")
            if new_day or not isinstance(open_mids, dict):
                open_mids = mids

            anchors = memory.get("anchors")
            if new_day or not isinstance(anchors, dict):
                anchors = self.refresh_price_anchors(mids)

            dishes_mem = dict(memory.get("dishes") or {})

            result: Dict[str, List[Order]] = {}
            for product, target in self.make_targets(day).items():
                orders = self.rebalance(product, target, state, self.MAX_ORDER_DIRECTIONAL)
                if orders:
                    result[product] = orders

            pair_orders = self.pair_regression_orders(state, day, open_mids, carry_mode)
            for product, orders in pair_orders.items():
                result[product] = result.get(product, []) + orders

            result.update(self.trade_snack_pairs(state, mids, anchors))
            result.update(self.trade_straw_basket(state, mids, anchors))

            dishes_orders, dishes_mem = self.trade_robot_dishes(
                state, mids, dishes_mem, regime_day=day, new_regime_tick=new_day
            )
            if dishes_orders:
                result[self.DISHES] = dishes_orders

            ironing_orders, ironing_mem = self.trade_robot_ironing(
                state, mids, memory.get("ironing") or {}
            )
            if ironing_orders:
                result[self.IRONING] = ironing_orders

            flow_orders, flow_mem = self.trade_robot_flow(state, mids, memory.get("flow") or {})
            for product, orders in flow_orders.items():
                result.setdefault(product, []).extend(orders)

            next_memory = {
                "day": day,
                "open_mids": open_mids,
                "carry_mode": carry_mode,
                "anchors": anchors,
                "dishes": dishes_mem,
                "ironing": ironing_mem,
                "flow": flow_mem,
            }
            return result, 0, json.dumps(next_memory, separators=(",", ":"))

        def refresh_price_anchors(self, mids: Dict[str, float]) -> Dict[str, float]:
            out: Dict[str, float] = {}
            for left, right, key in self.SNACK_PAIRS_KEYS:
                if left in mids and right in mids:
                    out[key] = float(mids[left] + mids[right])
            if self.STRAW_BASKET_PRODUCT in mids and all(p in mids for p in self.STRAW_BASKET_COEFS):
                linear = sum(coef * float(mids[p]) for p, coef in self.STRAW_BASKET_COEFS.items())
                out["straw"] = float(mids[self.STRAW_BASKET_PRODUCT]) - linear
            return out

        def make_targets(self, day: int) -> Dict[str, int]:
            targets: Dict[str, int] = {}
            for product, raw_target in self.BASE_TARGETS.items():
                target = int(round(raw_target * self.SCALE))
                targets[product] = max(-self.CAP, min(self.CAP, target))
            targets.update(self.PEBBLES_TARGETS_BY_DAY.get(day, {}))
            return targets

        def pair_regression_orders(
            self,
            state: TradingState,
            day: int,
            open_mids: Dict[str, float],
            carry_mode: bool,
        ) -> Dict[str, List[Order]]:
            mids = self.mids(state.order_depths)
            center = self.pebbles_center(mids)
            if center is None:
                return {}
            result: Dict[str, List[Order]] = {}
            skip_products = self.PAIR_SKIP_BY_DAY.get(day, set())
            cross_models = {} if carry_mode and day >= 4 else self.CROSS_OPEN_MODELS_BY_DAY.get(day, {})
            for product, models in self.PAIR_MODELS.items():
                if product in skip_products:
                    continue
                depth = state.order_depths.get(product)
                if depth is None or not depth.buy_orders or not depth.sell_orders:
                    continue
                fairs = []
                for reference, beta, intercept in models:
                    ref_mid = mids.get(reference)
                    if ref_mid is not None:
                        fairs.append(center + intercept + beta * (ref_mid - center))
                for reference, intercept, beta in cross_models.get(product, []):
                    ref_mid = mids.get(reference)
                    ref_open = open_mids.get(reference)
                    target_open = open_mids.get(product)
                    if ref_mid is not None and ref_open and target_open:
                        fair = float(target_open) * math.exp(intercept + beta * math.log(ref_mid / float(ref_open)))
                        fairs.extend([fair] * self.CROSS_WEIGHT)
                if not fairs:
                    continue

                fair = sum(fairs) / len(fairs)
                best_bid = max(depth.buy_orders)
                best_ask = min(depth.sell_orders)
                bid_price = best_bid + 1
                ask_price = best_ask - 1
                position = state.position.get(product, 0)
                long_cap = self.long_cap(product, day)
                buy_room = long_cap - position
                sell_room = self.PAIR_LIMIT + position
                orders: List[Order] = []

                if fair - bid_price >= self.PAIR_EDGE and buy_room > 0:
                    orders.append(Order(product, bid_price, min(self.PAIR_ORDER_SIZE, buy_room)))
                if ask_price - fair >= self.PAIR_EDGE and sell_room > 0:
                    orders.append(Order(product, ask_price, -min(self.PAIR_ORDER_SIZE, sell_room)))
                if orders:
                    result[product] = orders
            return result

        def long_cap(self, product: str, day: int) -> int:
            day_caps = self.LONG_CAPS_BY_DAY.get(day, self.LONG_CAPS_BY_DAY[3])
            return day_caps.get(product, self.PAIR_LIMIT)

        def has_pebbles_inventory(self, state: TradingState) -> bool:
            return any(state.position.get(product, 0) != 0 for product in self.PAIR_MODELS)

        def infer_day_from_pebbles_regime(self, state: TradingState) -> int | None:
            mids = self.mids(state.order_depths)
            if any(mids.get(product) is None for product in self.PEBBLES):
                return None
            ranking = sorted(self.PEBBLES, key=lambda product: mids[product], reverse=True)
            top_three = set(ranking[:3])
            bottom_two = set(ranking[-2:])
            if top_three == {"PEBBLES_L", "PEBBLES_M", "PEBBLES_XL"} and bottom_two == {"PEBBLES_S", "PEBBLES_XS"}:
                return 4
            if (
                ranking[0] == "PEBBLES_XL"
                and ranking[-1] == "PEBBLES_XS"
                and ranking.index("PEBBLES_L") < min(ranking.index("PEBBLES_M"), ranking.index("PEBBLES_S"))
            ):
                return 3
            return None

        def pebbles_center(self, mids: Dict[str, float]) -> float | None:
            values = [mids.get(product) for product in self.PEBBLES]
            if any(value is None for value in values):
                return None
            return sum(float(value) for value in values) / len(values)

        def mids(self, depths: Dict[str, OrderDepth]) -> Dict[str, float]:
            mids: Dict[str, float] = {}
            for product, depth in depths.items():
                if depth is not None and depth.buy_orders and depth.sell_orders:
                    mids[product] = (max(depth.buy_orders) + min(depth.sell_orders)) / 2.0
            return mids

        def rebalance(self, product: str, target: int, state: TradingState, max_order: int) -> List[Order]:
            if product in self.INTRO_HANDLED:
                return []
            depth = state.order_depths.get(product)
            if depth is None or not depth.buy_orders or not depth.sell_orders:
                return []
            position = state.position.get(product, 0)
            delta = target - position
            if delta == 0:
                return []

            best_bid = max(depth.buy_orders)
            best_ask = min(depth.sell_orders)
            if delta > 0:
                quantity = min(delta, max_order, abs(depth.sell_orders[best_ask]))
                return [Order(product, best_ask, quantity)] if quantity > 0 else []
            quantity = min(-delta, max_order, abs(depth.buy_orders[best_bid]))
            return [Order(product, best_bid, -quantity)] if quantity > 0 else []

        def load_state(self, trader_data: str) -> Dict:
            if not trader_data:
                return {}
            try:
                parsed = json.loads(trader_data)
                return parsed if isinstance(parsed, dict) else {}
            except Exception:
                return {}

        @staticmethod
        def best_prices(depth: OrderDepth) -> Tuple[int, int, int, int] | None:
            if not depth.buy_orders or not depth.sell_orders:
                return None
            best_bid = max(depth.buy_orders)
            best_ask = min(depth.sell_orders)
            if best_bid >= best_ask:
                return None
            return best_bid, depth.buy_orders[best_bid], best_ask, depth.sell_orders[best_ask]

        def snack_edges(self, state: TradingState, left: str, right: str) -> Tuple[float, float]:
            dl = state.order_depths.get(left)
            dr = state.order_depths.get(right)
            spread = 0.0
            if dl:
                bp = self.best_prices(dl)
                if bp:
                    spread += float(bp[2] - bp[0])
            if dr:
                bp = self.best_prices(dr)
                if bp:
                    spread += float(bp[2] - bp[0])
            half = spread / 2.0 if spread > 0 else 8.0
            take_edge = max(self.SNACK_EDGE_FLOOR, self.SNACK_EDGE_SPREAD_MUL * half)
            quote_edge = max(take_edge * 1.25, self.SNACK_QUOTE_MUL * half)
            return take_edge, quote_edge

        def straw_edges(self, state: TradingState) -> Tuple[float, float]:
            spreads = []
            for p in (*self.STRAW_BASKET_COEFS, self.STRAW_BASKET_PRODUCT):
                d = state.order_depths.get(p)
                if not d:
                    continue
                bp = self.best_prices(d)
                if bp:
                    spreads.append(float(bp[2] - bp[0]))
            avg_spread = sum(spreads) / max(len(spreads), 1)
            take_edge = max(self.STRAW_EDGE_FLOOR, self.STRAW_EDGE_SPREAD_MUL * avg_spread)
            quote_edge = max(take_edge * 1.3, self.STRAW_QUOTE_MUL * avg_spread)
            return take_edge, quote_edge

        def take_against_fair(
            self,
            product: str,
            depth: OrderDepth,
            fair: float,
            position: int,
            take_edge: float,
            quote_edge: float,
        ) -> List[Order]:
            prices = self.best_prices(depth)
            if prices is None:
                return []
            best_bid, bid_size, best_ask, ask_size = prices
            orders: List[Order] = []
            buy_room = self.LIMIT_INTRO - position
            sell_room = self.LIMIT_INTRO + position

            if buy_room > 0 and best_ask <= fair - take_edge:
                qty = min(buy_room, abs(ask_size), self.MAX_ORDER_INTRO)
                if qty > 0:
                    orders.append(Order(product, best_ask, qty))
                    buy_room -= qty

            if sell_room > 0 and best_bid >= fair + take_edge:
                qty = min(sell_room, bid_size, self.MAX_ORDER_INTRO)
                if qty > 0:
                    orders.append(Order(product, best_bid, -qty))
                    sell_room -= qty

            bid_price = int(math.floor(fair - quote_edge))
            ask_price = int(math.ceil(fair + quote_edge))
            if buy_room > 0 and bid_price < best_ask and bid_price >= best_bid:
                orders.append(Order(product, bid_price, min(buy_room, self.MAX_ORDER_INTRO)))
            if sell_room > 0 and ask_price > best_bid and ask_price <= best_ask:
                orders.append(Order(product, ask_price, -min(sell_room, self.MAX_ORDER_INTRO)))

            return orders

        def trade_snack_pairs(
            self, state: TradingState, mids: Dict[str, float], anchors: Dict[str, float]
        ) -> Dict[str, List[Order]]:
            result: Dict[str, List[Order]] = {}
            for left, right, key in self.SNACK_PAIRS_KEYS:
                anchor = anchors.get(key)
                if anchor is None or left not in mids or right not in mids:
                    continue
                take_edge, quote_edge = self.snack_edges(state, left, right)
                for product, partner in ((left, right), (right, left)):
                    fair = float(anchor) - mids[partner]
                    position = state.position.get(product, 0)
                    depth = state.order_depths.get(product)
                    if depth is None:
                        continue
                    orders = self.take_against_fair(
                        product, depth, fair, position, take_edge, quote_edge
                    )
                    if orders:
                        result.setdefault(product, []).extend(orders)
            return result

        def trade_straw_basket(
            self, state: TradingState, mids: Dict[str, float], anchors: Dict[str, float]
        ) -> Dict[str, List[Order]]:
            intercept = anchors.get("straw")
            product = self.STRAW_BASKET_PRODUCT
            if intercept is None or product not in mids:
                return {}
            if not all(p in mids for p in self.STRAW_BASKET_COEFS):
                return {}
            fair = float(intercept)
            for leg, coef in self.STRAW_BASKET_COEFS.items():
                fair += coef * mids[leg]
            position = state.position.get(product, 0)
            depth = state.order_depths.get(product)
            if depth is None:
                return {}
            take_edge, quote_edge = self.straw_edges(state)
            orders = self.take_against_fair(product, depth, fair, position, take_edge, quote_edge)
            return {product: orders} if orders else {}



        def trade_robot_dishes(
            self,
            state: TradingState,
            mids: Dict[str, float],
            mem: Dict,
            *,
            regime_day: int,
            new_regime_tick: bool,
        ) -> Tuple[List[Order], Dict]:
            product = self.DISHES
            depth = state.order_depths.get(product)
            if product not in mids or depth is None:
                base = dict(mem)
                base.setdefault("prev_mid", None)
                base.setdefault("vol", 0.0)
                base.setdefault("vol_baseline", None)
                return [], base

            mid = mids[product]
            prev_mid = mem.get("prev_mid")
            prev_vol = float(mem.get("vol", 0.0))
            prev_baseline = mem.get("vol_baseline")

            if new_regime_tick:
                prev_baseline = None

            if prev_mid is None:
                return [], {"prev_mid": mid, "vol": prev_vol, "vol_baseline": prev_baseline}

            move = mid - prev_mid
            vol = self.DISHES_VOL_DECAY * prev_vol + (1.0 - self.DISHES_VOL_DECAY) * abs(move)

            vol_sample = max(vol, abs(move), 1e-6)
            if prev_baseline is None:
                vol_baseline_out = vol_sample
            else:
                vol_baseline_out = (
                    self.DISHES_VOL_BASELINE_DECAY * float(prev_baseline)
                    + (1.0 - self.DISHES_VOL_BASELINE_DECAY) * vol_sample
                )

            burst = prev_baseline is not None and (
                vol >= self.DISHES_BURST_VS_BASELINE * float(prev_baseline)
                or abs(move) >= self.DISHES_BURST_VS_BASELINE * float(prev_baseline)
            )
            shen = burst or regime_day >= 4
            thresh = float(self.DISHES_VOL_GATE) * (
                self.DISHES_GATE_SHEN_FACTOR if shen else 1.0
            )

            next_state = {"prev_mid": mid, "vol": vol, "vol_baseline": vol_baseline_out}

            if vol < thresh or abs(move) < thresh:
                return [], next_state

            fair = mid - self.DISHES_REVERSION * move
            position = state.position.get(product, 0)
            take_edge = float(self.DISHES_TAKE_EDGE)
            orders = self.take_against_fair(
                product,
                depth,
                fair,
                position,
                take_edge,
                take_edge + 3.0,
            )
            return orders, next_state

        def trade_robot_ironing(self, state: TradingState, mids: Dict[str, float], mem: Dict) -> Tuple[List[Order], Dict]:
            product = self.IRONING
            depth = state.order_depths.get(product)
            if product not in mids or depth is None:
                return [], {"prev_mid": mem.get("prev_mid")}
            mid = mids[product]
            prev_mid = mem.get("prev_mid")
            next_state = {"prev_mid": mid}
            if prev_mid is None:
                return [], next_state
            move = mid - prev_mid
            signal = -self.IRONING_REVERSION * move
            position = state.position.get(product, 0)
            bp = self.best_prices(depth)
            thresh = abs(float(bp[2] - bp[0])) * self.IRONING_SPREAD_FRAC if bp else 1.5
            orders = self.quote_inside_spread(product, depth, position, signal, max(0.5, thresh))
            return orders, next_state

        def update_flow_signal(
            self,
            mid: float,
            market_trades: List,
            prev_signal: float,
            weight: float,
        ) -> float:
            signal = self.FLOW_DECAY * prev_signal
            for trade in market_trades:
                side = 1 if trade.price > mid else -1 if trade.price < mid else 0
                signal += weight * side * min(3, trade.quantity)
            return signal

        def trade_robot_flow(
            self,
            state: TradingState,
            mids: Dict[str, float],
            mem: Dict,
        ) -> Tuple[Dict[str, List[Order]], Dict]:
            result: Dict[str, List[Order]] = {}
            next_signals: Dict[str, float] = {}
            product = self.LAUNDRY
            if product not in mids:
                return {}, {}

            depth = state.order_depths.get(product)
            if depth is None:
                return {}, {}

            mid = mids[product]
            prev_signal = float(mem.get(product, 0.0))
            signal = self.update_flow_signal(
                mid,
                state.market_trades.get(product, []),
                prev_signal,
                self.FLOW_FADE_WEIGHT,
            )
            next_signals[product] = signal
            position = state.position.get(product, 0)
            bp = self.best_prices(depth)
            thresh = max(
                self.FLOW_THRESHOLD_FLOOR,
                abs(float(bp[2] - bp[0])) * self.FLOW_SPREAD_FRAC,
            )
            orders = self.quote_inside_spread(product, depth, position, signal, thresh)
            if orders:
                result[product] = orders
            return result, next_signals

        def quote_inside_spread(
            self,
            product: str,
            depth: OrderDepth,
            position: int,
            signal: float,
            threshold: float,
        ) -> List[Order]:
            prices = self.best_prices(depth)
            if prices is None:
                return []
            best_bid, _, best_ask, _ = prices
            if best_ask - best_bid < self.PASSIVE_MIN_SPREAD:
                return []
            if abs(signal) < threshold:
                return []
            cap = self.PASSIVE_INVENTORY
            if signal > 0 and position < cap:
                qty = min(self.PASSIVE_QTY, cap - position)
                return [Order(product, best_bid + 1, qty)]
            if signal < 0 and position > -cap:
                qty = min(self.PASSIVE_QTY, cap + position)
                return [Order(product, best_ask - 1, -qty)]
            return []

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

intro_max_strategy = __build_intro_max_strategy()
traders.ROUND_5.intro_max_strategy = intro_max_strategy
# --- end pasted traders/ROUND_5/intro_max_strategy.py ---

Trader = intro_max_strategy.Trader

__all__ = ['Trader']
