# Auto-generated by `uv run compile`.
# Do not edit by hand; edit the source trader and recompile.

class __CompiledModule:
    pass

traders = __CompiledModule()
traders.ROUND_5 = __CompiledModule()

# --- begin pasted traders/ROUND_5/strategy_v5_imbalance_aware.py ---
def __build_strategy_v5_imbalance_aware():
    from datamodel import OrderDepth, UserId, TradingState, Order
    from typing import Dict

    class Trader:
        """
        V5: Order book imbalance + momentum strategy.

        Key additions from v4:
        1. Detect buy/sell pressure from order book imbalance
        2. Adjust bids/asks based on imbalance direction
        3. Scale position size by imbalance strength
        4. More sophisticated momentum window
        """

        FAMILIES = {
            'SNACKPACK': {
                'products': ['SNACKPACK_CHOCOLATE', 'SNACKPACK_PISTACHIO', 'SNACKPACK_RASPBERRY',
                            'SNACKPACK_STRAWBERRY', 'SNACKPACK_VANILLA'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 110, 'vol_scale': 1.15
            },
            'GALAXY_SOUNDS': {
                'products': ['GALAXY_SOUNDS_BLACK_HOLES', 'GALAXY_SOUNDS_DARK_MATTER',
                            'GALAXY_SOUNDS_PLANETARY_RINGS', 'GALAXY_SOUNDS_SOLAR_FLAMES', 'GALAXY_SOUNDS_SOLAR_WINDS'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 100, 'vol_scale': 1.0
            },
            'OXYGEN_SHAKE': {
                'products': ['OXYGEN_SHAKE_CHOCOLATE', 'OXYGEN_SHAKE_EVENING_BREATH',
                            'OXYGEN_SHAKE_GARLIC', 'OXYGEN_SHAKE_MINT', 'OXYGEN_SHAKE_MORNING_BREATH'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 95, 'vol_scale': 1.0
            },
            'UV_VISOR': {
                'products': ['UV_VISOR_AMBER', 'UV_VISOR_MAGENTA', 'UV_VISOR_ORANGE',
                            'UV_VISOR_RED', 'UV_VISOR_YELLOW'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 90, 'vol_scale': 1.0
            },
            'PEBBLES': {
                'products': ['PEBBLES_L', 'PEBBLES_M', 'PEBBLES_S', 'PEBBLES_XL', 'PEBBLES_XS'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 85, 'vol_scale': 0.95
            },
            'PANEL': {
                'products': ['PANEL_1X2', 'PANEL_1X4', 'PANEL_2X2', 'PANEL_2X4', 'PANEL_4X4'],
                'base_bid': -3, 'base_ask': 3, 'max_pos': 75, 'vol_scale': 0.9
            },
            'SLEEP_POD': {
                'products': ['SLEEP_POD_COTTON', 'SLEEP_POD_LAMB_WOOL', 'SLEEP_POD_NYLON',
                            'SLEEP_POD_POLYESTER', 'SLEEP_POD_SUEDE'],
                'base_bid': -3, 'base_ask': 3, 'max_pos': 70, 'vol_scale': 0.9
            },
            'MICROCHIP': {
                'products': ['MICROCHIP_CIRCLE', 'MICROCHIP_OVAL', 'MICROCHIP_RECTANGLE',
                            'MICROCHIP_SQUARE', 'MICROCHIP_TRIANGLE'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 55, 'vol_scale': 0.8
            },
            'TRANSLATOR': {
                'products': ['TRANSLATOR_ASTRO_BLACK', 'TRANSLATOR_ECLIPSE_CHARCOAL',
                            'TRANSLATOR_GRAPHITE_MIST', 'TRANSLATOR_SPACE_GRAY', 'TRANSLATOR_VOID_BLUE'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 60, 'vol_scale': 0.8
            },
            'ROBOT': {
                'products': ['ROBOT_DISHES', 'ROBOT_IRONING', 'ROBOT_LAUNDRY',
                            'ROBOT_MOPPING', 'ROBOT_VACUUMING'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 50, 'vol_scale': 0.65
            },
        }

        PROBLEM_PRODUCTS = {
            'SLEEP_POD_LAMB_WOOL': {'max_pos_mult': 0.5, 'vol_mult': 0.4, 'offset_mult': 1.6},
            'SLEEP_POD_NYLON': {'max_pos_mult': 0.5, 'vol_mult': 0.4, 'offset_mult': 1.6},
            'SNACKPACK_CHOCOLATE': {'max_pos_mult': 0.7, 'vol_mult': 0.7, 'offset_mult': 1.3},
            'SNACKPACK_PISTACHIO': {'max_pos_mult': 0.7, 'vol_mult': 0.7, 'offset_mult': 1.3},
            'TRANSLATOR_ASTRO_BLACK': {'max_pos_mult': 0.5, 'vol_mult': 0.5, 'offset_mult': 1.5},
            'TRANSLATOR_SPACE_GRAY': {'max_pos_mult': 0.5, 'vol_mult': 0.5, 'offset_mult': 1.5},
            'UV_VISOR_AMBER': {'max_pos_mult': 0.4, 'vol_mult': 0.4, 'offset_mult': 1.6},
            'UV_VISOR_ORANGE': {'max_pos_mult': 0.6, 'vol_mult': 0.6, 'offset_mult': 1.3},
        }

        def __init__(self):
            self.position = {}
            self.prices = {}

        def bid(self):
            return 15

        def get_family(self, product: str) -> Dict:
            for family_name, family_data in self.FAMILIES.items():
                if product in family_data['products']:
                    return family_data
            return self.FAMILIES['ROBOT']

        def calculate_momentum(self, product: str, current_mid: float) -> float:
            """Return momentum scalar: -2 to 2"""
            if product not in self.prices:
                self.prices[product] = []

            self.prices[product].append(current_mid)
            if len(self.prices[product]) > 20:
                self.prices[product].pop(0)

            if len(self.prices[product]) < 6:
                return 0.0

            # Recent vs older
            recent = sum(self.prices[product][-3:]) / 3
            older = sum(self.prices[product][-6:-3]) / 3
            base_trend = (recent - older) / older if older != 0 else 0

            # Strength
            momentum = min(2.0, max(-2.0, base_trend * 20))  # Scale to -2..2
            return momentum

        def calculate_imbalance(self, order_depth: OrderDepth) -> float:
            """
            Return imbalance ratio: -1 (more sells) to 1 (more buys)
            Weighted by best levels.
            """
            if not order_depth.buy_orders or not order_depth.sell_orders:
                return 0.0

            best_bid_vol = list(order_depth.buy_orders.values())[0]
            best_ask_vol = list(order_depth.sell_orders.values())[0]

            total = best_bid_vol + best_ask_vol
            if total == 0:
                return 0.0

            imbalance = (best_bid_vol - best_ask_vol) / total
            return imbalance

        def run(self, state: TradingState):
            result = {}
            conversions = 0

            for product in state.order_depths.keys():
                if product not in self.position:
                    self.position[product] = 0

            for product in state.order_depths.keys():
                order_depth = state.order_depths[product]
                family = self.get_family(product)
                orders = []

                # Mid price
                best_bid = max(order_depth.buy_orders.keys()) if order_depth.buy_orders else 10000
                best_ask = min(order_depth.sell_orders.keys()) if order_depth.sell_orders else 10000
                mid = (best_bid + best_ask) / 2 if order_depth.buy_orders and order_depth.sell_orders else best_bid if order_depth.buy_orders else best_ask

                # Momentum and imbalance
                momentum = self.calculate_momentum(product, mid)
                imbalance = self.calculate_imbalance(order_depth)

                # Base parameters
                bid_offset = family['base_bid']
                ask_offset = family['base_ask']
                max_pos = family['max_pos']
                vol_scale = family['vol_scale']

                # Problem product adjustments
                if product in self.PROBLEM_PRODUCTS:
                    adj = self.PROBLEM_PRODUCTS[product]
                    max_pos = int(max_pos * adj['max_pos_mult'])
                    vol_scale = vol_scale * adj['vol_mult']
                    bid_offset = int(bid_offset * adj['offset_mult'])
                    ask_offset = int(ask_offset * adj['offset_mult'])

                # Momentum adjustment
                if momentum > 0.5:
                    bid_offset = max(bid_offset - 1, -6)
                elif momentum < -0.5:
                    ask_offset = min(ask_offset + 1, 6)

                # Imbalance adjustment: shift our quotes toward stronger side
                if imbalance > 0.3:  # More buy pressure
                    bid_offset = max(bid_offset - 1, -6)
                elif imbalance < -0.3:  # More sell pressure
                    ask_offset = min(ask_offset + 1, 6)

                # Volumes
                bid_vol = max(1, int((list(order_depth.buy_orders.values())[0] if order_depth.buy_orders else 10) * vol_scale))
                ask_vol = max(1, int((list(order_depth.sell_orders.values())[0] if order_depth.sell_orders else 10) * vol_scale))

                # Adjust volume by imbalance (scale up on stronger side)
                if imbalance > 0.2:
                    bid_vol = int(bid_vol * 1.1)
                elif imbalance < -0.2:
                    ask_vol = int(ask_vol * 1.1)

                # Place orders
                bid_price = int(mid) + bid_offset
                ask_price = int(mid) + ask_offset

                current_pos = self.position[product]

                if current_pos < max_pos:
                    orders.append(Order(product, bid_price, bid_vol))

                if current_pos > -max_pos:
                    orders.append(Order(product, ask_price, ask_vol))

                result[product] = orders

            return result, conversions, ""

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

strategy_v5_imbalance_aware = __build_strategy_v5_imbalance_aware()
traders.ROUND_5.strategy_v5_imbalance_aware = strategy_v5_imbalance_aware
# --- end pasted traders/ROUND_5/strategy_v5_imbalance_aware.py ---

Trader = strategy_v5_imbalance_aware.Trader

__all__ = ['Trader']
