# Auto-generated by `uv run compile`.
# Do not edit by hand; edit the source trader and recompile.

class __CompiledModule:
    pass

traders = __CompiledModule()
traders.ROUND_5 = __CompiledModule()

# --- begin pasted traders/ROUND_5/strategy_v4_momentum_selective.py ---
def __build_strategy_v4_momentum_selective():
    from datamodel import OrderDepth, UserId, TradingState, Order
    from typing import Dict, List

    class Trader:
        """
        V4: Momentum-driven market maker with selective entry.

        Key refinement from v2:
        - Stronger momentum detection (3+ price ticks)
        - More selective on low-spread products
        - Deeper mid-range price tracking
        - Better handling of reverting/trending products
        """

        FAMILIES = {
            'SNACKPACK': {
                'products': ['SNACKPACK_CHOCOLATE', 'SNACKPACK_PISTACHIO', 'SNACKPACK_RASPBERRY',
                            'SNACKPACK_STRAWBERRY', 'SNACKPACK_VANILLA'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 100, 'vol_scale': 1.1, 'trend_sensitivity': 2
            },
            'GALAXY_SOUNDS': {
                'products': ['GALAXY_SOUNDS_BLACK_HOLES', 'GALAXY_SOUNDS_DARK_MATTER',
                            'GALAXY_SOUNDS_PLANETARY_RINGS', 'GALAXY_SOUNDS_SOLAR_FLAMES', 'GALAXY_SOUNDS_SOLAR_WINDS'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 95, 'vol_scale': 1.0, 'trend_sensitivity': 1.5
            },
            'OXYGEN_SHAKE': {
                'products': ['OXYGEN_SHAKE_CHOCOLATE', 'OXYGEN_SHAKE_EVENING_BREATH',
                            'OXYGEN_SHAKE_GARLIC', 'OXYGEN_SHAKE_MINT', 'OXYGEN_SHAKE_MORNING_BREATH'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 90, 'vol_scale': 1.0, 'trend_sensitivity': 1.5
            },
            'UV_VISOR': {
                'products': ['UV_VISOR_AMBER', 'UV_VISOR_MAGENTA', 'UV_VISOR_ORANGE',
                            'UV_VISOR_RED', 'UV_VISOR_YELLOW'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 85, 'vol_scale': 1.0, 'trend_sensitivity': 1.5
            },
            'PEBBLES': {
                'products': ['PEBBLES_L', 'PEBBLES_M', 'PEBBLES_S', 'PEBBLES_XL', 'PEBBLES_XS'],
                'base_bid': -4, 'base_ask': 4, 'max_pos': 80, 'vol_scale': 0.95, 'trend_sensitivity': 1.5
            },
            'PANEL': {
                'products': ['PANEL_1X2', 'PANEL_1X4', 'PANEL_2X2', 'PANEL_2X4', 'PANEL_4X4'],
                'base_bid': -3, 'base_ask': 3, 'max_pos': 70, 'vol_scale': 0.9, 'trend_sensitivity': 1.0
            },
            'SLEEP_POD': {
                'products': ['SLEEP_POD_COTTON', 'SLEEP_POD_LAMB_WOOL', 'SLEEP_POD_NYLON',
                            'SLEEP_POD_POLYESTER', 'SLEEP_POD_SUEDE'],
                'base_bid': -3, 'base_ask': 3, 'max_pos': 65, 'vol_scale': 0.85, 'trend_sensitivity': 1.2
            },
            'MICROCHIP': {
                'products': ['MICROCHIP_CIRCLE', 'MICROCHIP_OVAL', 'MICROCHIP_RECTANGLE',
                            'MICROCHIP_SQUARE', 'MICROCHIP_TRIANGLE'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 50, 'vol_scale': 0.75, 'trend_sensitivity': 0.8
            },
            'TRANSLATOR': {
                'products': ['TRANSLATOR_ASTRO_BLACK', 'TRANSLATOR_ECLIPSE_CHARCOAL',
                            'TRANSLATOR_GRAPHITE_MIST', 'TRANSLATOR_SPACE_GRAY', 'TRANSLATOR_VOID_BLUE'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 55, 'vol_scale': 0.75, 'trend_sensitivity': 0.9
            },
            'ROBOT': {
                'products': ['ROBOT_DISHES', 'ROBOT_IRONING', 'ROBOT_LAUNDRY',
                            'ROBOT_MOPPING', 'ROBOT_VACUUMING'],
                'base_bid': -2, 'base_ask': 2, 'max_pos': 45, 'vol_scale': 0.6, 'trend_sensitivity': 0.7
            },
        }

        # Known problem products - be more conservative
        PROBLEM_PRODUCTS = {
            'SLEEP_POD_LAMB_WOOL': {'max_pos_mult': 0.6, 'vol_mult': 0.5, 'offset_mult': 1.5},
            'SLEEP_POD_NYLON': {'max_pos_mult': 0.6, 'vol_mult': 0.5, 'offset_mult': 1.5},
            'SNACKPACK_CHOCOLATE': {'max_pos_mult': 0.7, 'vol_mult': 0.7, 'offset_mult': 1.3},
            'SNACKPACK_PISTACHIO': {'max_pos_mult': 0.7, 'vol_mult': 0.7, 'offset_mult': 1.3},
            'TRANSLATOR_ASTRO_BLACK': {'max_pos_mult': 0.6, 'vol_mult': 0.6, 'offset_mult': 1.4},
            'TRANSLATOR_SPACE_GRAY': {'max_pos_mult': 0.6, 'vol_mult': 0.6, 'offset_mult': 1.4},
            'UV_VISOR_AMBER': {'max_pos_mult': 0.5, 'vol_mult': 0.5, 'offset_mult': 1.5},
            'UV_VISOR_ORANGE': {'max_pos_mult': 0.7, 'vol_mult': 0.7, 'offset_mult': 1.2},
        }

        def __init__(self):
            self.position = {}
            self.prices = {}  # Keep longer history for better momentum

        def bid(self):
            return 15

        def get_family(self, product: str) -> Dict:
            for family_name, family_data in self.FAMILIES.items():
                if product in family_data['products']:
                    return family_data
            return self.FAMILIES['ROBOT']

        def calculate_momentum(self, product: str, current_mid: float) -> int:
            """
            Calculate momentum: -1 (down), 0 (flat), 1 (up)
            Based on price acceleration over recent history.
            """
            if product not in self.prices:
                self.prices[product] = []

            self.prices[product].append(current_mid)
            if len(self.prices[product]) > 15:
                self.prices[product].pop(0)

            if len(self.prices[product]) < 5:
                return 0

            # Recent trend (last 3 vs previous 3)
            recent = sum(self.prices[product][-3:]) / 3
            prev = sum(self.prices[product][-6:-3]) / 3
            trend = 1 if recent > prev else (-1 if recent < prev else 0)

            # Acceleration: is trend strengthening?
            if len(self.prices[product]) >= 9:
                accel_recent = sum(self.prices[product][-3:]) / 3
                accel_mid = sum(self.prices[product][-6:-3]) / 3
                accel_old = sum(self.prices[product][-9:-6]) / 3
                accel = (accel_recent - accel_mid) - (accel_mid - accel_old)
                if accel > 0.5 and trend > 0:
                    return 2  # Strong uptrend
                elif accel < -0.5 and trend < 0:
                    return -2  # Strong downtrend

            return trend

        def run(self, state: TradingState):
            result = {}
            conversions = 0

            for product in state.order_depths.keys():
                if product not in self.position:
                    self.position[product] = 0

            for product in state.order_depths.keys():
                order_depth = state.order_depths[product]
                family = self.get_family(product)
                orders = []

                # Calculate mid
                best_bid = max(order_depth.buy_orders.keys()) if order_depth.buy_orders else 10000
                best_ask = min(order_depth.sell_orders.keys()) if order_depth.sell_orders else 10000
                mid = (best_bid + best_ask) / 2 if order_depth.buy_orders and order_depth.sell_orders else best_bid if order_depth.buy_orders else best_ask

                # Get momentum
                momentum = self.calculate_momentum(product, mid)

                # Base parameters
                bid_offset = family['base_bid']
                ask_offset = family['base_ask']
                max_pos = family['max_pos']
                vol_scale = family['vol_scale']

                # Apply problem product adjustments
                if product in self.PROBLEM_PRODUCTS:
                    adj = self.PROBLEM_PRODUCTS[product]
                    max_pos = int(max_pos * adj['max_pos_mult'])
                    vol_scale = vol_scale * adj['vol_mult']
                    bid_offset = int(bid_offset * adj['offset_mult'])
                    ask_offset = int(ask_offset * adj['offset_mult'])

                # Apply momentum adjustment
                trend_sens = family['trend_sensitivity']
                if momentum > 0:
                    bid_offset = max(bid_offset - int(trend_sens), -5)  # More aggressive on bid
                elif momentum < 0:
                    ask_offset = min(ask_offset + int(trend_sens), 5)   # More aggressive on ask

                # Calculate volumes
                bid_vol = max(1, int((list(order_depth.buy_orders.values())[0] if order_depth.buy_orders else 10) * vol_scale))
                ask_vol = max(1, int((list(order_depth.sell_orders.values())[0] if order_depth.sell_orders else 10) * vol_scale))

                # Place orders
                bid_price = int(mid) + bid_offset
                ask_price = int(mid) + ask_offset

                current_pos = self.position[product]

                if current_pos < max_pos:
                    orders.append(Order(product, bid_price, bid_vol))

                if current_pos > -max_pos:
                    orders.append(Order(product, ask_price, ask_vol))

                result[product] = orders

            return result, conversions, ""

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

strategy_v4_momentum_selective = __build_strategy_v4_momentum_selective()
traders.ROUND_5.strategy_v4_momentum_selective = strategy_v4_momentum_selective
# --- end pasted traders/ROUND_5/strategy_v4_momentum_selective.py ---

Trader = strategy_v4_momentum_selective.Trader

__all__ = ['Trader']
