# Auto-generated by `uv run compile`.
# Do not edit by hand; edit the source trader and recompile.

class __CompiledModule:
    pass

traders = __CompiledModule()
traders.ROUND_5 = __CompiledModule()

# --- begin pasted traders/ROUND_5/trader_combined_strats.py ---
def __build_trader_combined_strats():
    """trader_combined_strats — strategy_v4 MM baseline + pair-trade overlay.

    Findings from notebooks/ROUND_5/group_explore.ipynb:

    1. 1-tick within-group correlations are noise (~0.005).
    2. At 1000-tick horizons, every group has at least one pair with |corr| >= 0.20.
       SNACKPACK has 4 pairs at |corr| >= 0.86 — basically deterministic linear combos.
    3. Bot flow is identical across 7 of 8 groups (MICROCHIP excepted), so a single
       MM template works across them.
    4. Cross-day stability is tight, so OLS coefficients fit on day 2/3/4 hold forward.

    Architecture:
    - Baseline: copy of strategy_v4_momentum_selective (the best non-pair trader at $2.96M).
      Family-keyed bid/ask offsets, momentum-driven offset adjustments, winner/loser tilts.
    - Overlay: precomputed pair regressions. Residual z = (a - beta*b - alpha)/std.
      When |z| >= Z_ENTRY, push a small directional position via passive orders inside
      the spread. Capped per-pair so the overlay can't dominate the MM.

    The overlay does NOT change MM quotes (no price bias) and does NOT cross the spread
    (no take orders) — it adds passive at-mid orders. This preserves the $2.96M baseline.
    """

    from datamodel import OrderDepth, TradingState, Order
    from typing import Dict, List, Tuple


    PairModel = Tuple[str, str, float, float, float, float]  # a, b, beta, alpha, std, weight


    class Trader:
        # ---- Pair-trade models (precomputed offline, see analysis notebook) ----
        PAIR_MODELS: List[PairModel] = [
            # SNACKPACK — strongest pairs (|corr| >= 0.86)
            ('SNACKPACK_CHOCOLATE',         'SNACKPACK_VANILLA',           -1.0411, 20356.14,  75.84, 0.96),
            ('SNACKPACK_RASPBERRY',         'SNACKPACK_STRAWBERRY',        -0.1932, 12146.24, 154.61, 0.94),
            ('SNACKPACK_PISTACHIO',         'SNACKPACK_RASPBERRY',         -0.5492, 15030.23, 162.66, 0.88),
            ('SNACKPACK_PISTACHIO',         'SNACKPACK_STRAWBERRY',        -0.2276, 11932.18, 168.25, 0.86),
            # PANEL
            ('PANEL_2X2',                   'PANEL_4X4',                   -0.7295, 16783.08, 586.67, 0.42),
            ('PANEL_1X2',                   'PANEL_2X4',                   +0.1210,  7560.04, 585.01, 0.32),
            # TRANSLATOR
            ('TRANSLATOR_ASTRO_BLACK',      'TRANSLATOR_GRAPHITE_MIST',    -0.1887, 11287.81, 480.59, 0.32),
            ('TRANSLATOR_ECLIPSE_CHARCOAL', 'TRANSLATOR_SPACE_GRAY',       -0.1067, 10820.59, 351.56, 0.29),
            # UV_VISOR
            ('UV_VISOR_AMBER',              'UV_VISOR_ORANGE',             -1.2867, 21327.68, 701.38, 0.30),
            ('UV_VISOR_MAGENTA',            'UV_VISOR_RED',                +0.3266,  7498.44, 582.75, 0.26),
            ('UV_VISOR_ORANGE',             'UV_VISOR_RED',                +0.3898,  6114.56, 500.69, 0.20),
            # GALAXY_SOUNDS
            ('GALAXY_SOUNDS_BLACK_HOLES',   'GALAXY_SOUNDS_SOLAR_FLAMES',  -0.2493, 14232.51, 951.84, 0.28),
            ('GALAXY_SOUNDS_BLACK_HOLES',   'GALAXY_SOUNDS_SOLAR_WINDS',   +0.8243,  2863.48, 848.33, 0.26),
            # MICROCHIP
            ('MICROCHIP_CIRCLE',            'MICROCHIP_RECTANGLE',         +0.0981,  8358.32, 527.37, 0.24),
            ('MICROCHIP_CIRCLE',            'MICROCHIP_OVAL',              -0.1426, 10381.11, 484.36, 0.22),
            ('MICROCHIP_RECTANGLE',         'MICROCHIP_TRIANGLE',          +0.3055,  5773.67, 707.62, 0.20),
            # OXYGEN_SHAKE
            ('OXYGEN_SHAKE_EVENING_BREATH', 'OXYGEN_SHAKE_GARLIC',         -0.0569,  9951.05, 396.11, 0.23),
            # SLEEP_POD
            ('SLEEP_POD_COTTON',            'SLEEP_POD_SUEDE',             +0.6914,  3647.01, 633.09, 0.21),
        ]

        # Overlay tunables — swept against the v4 baseline ($2.96M).
        # Best combo Z_ENTRY=1.0, OV=30 yielded $3.43M (+15.6%).
        # Loser-skip *hurts* (3.33M) — the pair signal correctly fades losers when
        # overextended, so we let the overlay run on every product.
        Z_ENTRY = 1.0         # below this we don't lean
        Z_MAX = 3.0           # cap on sizing
        OVERLAY_PER_PAIR = 30 # max units pushed by a single pair at z=Z_MAX

        # ---- v4 family-based MM params (unchanged from baseline) ---------------
        FAMILIES: Dict[str, Dict] = {
            'SNACKPACK':     {'products': ['SNACKPACK_CHOCOLATE', 'SNACKPACK_PISTACHIO', 'SNACKPACK_RASPBERRY',
                                           'SNACKPACK_STRAWBERRY', 'SNACKPACK_VANILLA'],
                              'base_bid': -2, 'base_ask': 2, 'max_pos': 120, 'vol_scale': 1.2},
            'GALAXY_SOUNDS': {'products': ['GALAXY_SOUNDS_BLACK_HOLES', 'GALAXY_SOUNDS_DARK_MATTER',
                                           'GALAXY_SOUNDS_PLANETARY_RINGS', 'GALAXY_SOUNDS_SOLAR_FLAMES',
                                           'GALAXY_SOUNDS_SOLAR_WINDS'],
                              'base_bid': -4, 'base_ask': 4, 'max_pos': 105, 'vol_scale': 1.05},
            'OXYGEN_SHAKE':  {'products': ['OXYGEN_SHAKE_CHOCOLATE', 'OXYGEN_SHAKE_EVENING_BREATH',
                                           'OXYGEN_SHAKE_GARLIC', 'OXYGEN_SHAKE_MINT', 'OXYGEN_SHAKE_MORNING_BREATH'],
                              'base_bid': -4, 'base_ask': 4, 'max_pos': 100, 'vol_scale': 1.05},
            'UV_VISOR':      {'products': ['UV_VISOR_AMBER', 'UV_VISOR_MAGENTA', 'UV_VISOR_ORANGE',
                                           'UV_VISOR_RED', 'UV_VISOR_YELLOW'],
                              'base_bid': -4, 'base_ask': 4, 'max_pos': 95, 'vol_scale': 1.05},
            'PEBBLES':       {'products': ['PEBBLES_L', 'PEBBLES_M', 'PEBBLES_S', 'PEBBLES_XL', 'PEBBLES_XS'],
                              'base_bid': -4, 'base_ask': 4, 'max_pos': 90, 'vol_scale': 1.0},
            'PANEL':         {'products': ['PANEL_1X2', 'PANEL_1X4', 'PANEL_2X2', 'PANEL_2X4', 'PANEL_4X4'],
                              'base_bid': -3, 'base_ask': 3, 'max_pos': 75, 'vol_scale': 0.95},
            'SLEEP_POD':     {'products': ['SLEEP_POD_COTTON', 'SLEEP_POD_LAMB_WOOL', 'SLEEP_POD_NYLON',
                                           'SLEEP_POD_POLYESTER', 'SLEEP_POD_SUEDE'],
                              'base_bid': -3, 'base_ask': 3, 'max_pos': 70, 'vol_scale': 0.9},
            'MICROCHIP':     {'products': ['MICROCHIP_CIRCLE', 'MICROCHIP_OVAL', 'MICROCHIP_RECTANGLE',
                                           'MICROCHIP_SQUARE', 'MICROCHIP_TRIANGLE'],
                              'base_bid': -2, 'base_ask': 2, 'max_pos': 55, 'vol_scale': 0.8},
            'TRANSLATOR':    {'products': ['TRANSLATOR_ASTRO_BLACK', 'TRANSLATOR_ECLIPSE_CHARCOAL',
                                           'TRANSLATOR_GRAPHITE_MIST', 'TRANSLATOR_SPACE_GRAY', 'TRANSLATOR_VOID_BLUE'],
                              'base_bid': -2, 'base_ask': 2, 'max_pos': 60, 'vol_scale': 0.8},
            'ROBOT':         {'products': ['ROBOT_DISHES', 'ROBOT_IRONING', 'ROBOT_LAUNDRY',
                                           'ROBOT_MOPPING', 'ROBOT_VACUUMING'],
                              'base_bid': -2, 'base_ask': 2, 'max_pos': 50, 'vol_scale': 0.65},
        }

        WINNER_PRODUCTS = {
            'SNACKPACK_RASPBERRY':        {'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'SNACKPACK_STRAWBERRY':       {'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'SNACKPACK_VANILLA':          {'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'TRANSLATOR_ECLIPSE_CHARCOAL':{'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'TRANSLATOR_VOID_BLUE':       {'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'UV_VISOR_MAGENTA':           {'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'UV_VISOR_RED':               {'max_pos_mult': 1.1, 'vol_mult': 1.1},
            'UV_VISOR_YELLOW':            {'max_pos_mult': 1.1, 'vol_mult': 1.1},
        }

        LOSER_PRODUCTS = {
            'SLEEP_POD_LAMB_WOOL':       {'max_pos_mult': 0.4, 'vol_mult': 0.3, 'offset_mult': 1.8},
            'SLEEP_POD_NYLON':           {'max_pos_mult': 0.4, 'vol_mult': 0.3, 'offset_mult': 1.8},
            'SNACKPACK_CHOCOLATE':       {'max_pos_mult': 0.6, 'vol_mult': 0.6, 'offset_mult': 1.4},
            'SNACKPACK_PISTACHIO':       {'max_pos_mult': 0.6, 'vol_mult': 0.6, 'offset_mult': 1.4},
            'TRANSLATOR_ASTRO_BLACK':    {'max_pos_mult': 0.4, 'vol_mult': 0.4, 'offset_mult': 1.6},
            'TRANSLATOR_SPACE_GRAY':     {'max_pos_mult': 0.4, 'vol_mult': 0.4, 'offset_mult': 1.6},
            'UV_VISOR_AMBER':            {'max_pos_mult': 0.3, 'vol_mult': 0.3, 'offset_mult': 1.8},
            'UV_VISOR_ORANGE':           {'max_pos_mult': 0.5, 'vol_mult': 0.5, 'offset_mult': 1.5},
        }

        def __init__(self):
            self.prices: Dict[str, List[float]] = {}

        # ---- v4 helpers --------------------------------------------------------

        def get_family(self, product: str) -> Dict:
            for cfg in self.FAMILIES.values():
                if product in cfg['products']:
                    return cfg
            return self.FAMILIES['ROBOT']

        def calculate_momentum(self, product: str, current_mid: float) -> int:
            history = self.prices.setdefault(product, [])
            history.append(current_mid)
            if len(history) > 20:
                history.pop(0)
            if len(history) < 6:
                return 0
            recent_3 = sum(history[-3:]) / 3
            prev_3 = sum(history[-6:-3]) / 3
            base = 1 if recent_3 > prev_3 else (-1 if recent_3 < prev_3 else 0)
            if len(history) >= 12 and base != 0:
                prev_6 = sum(history[-12:-6]) / 6
                curr_6 = sum(history[-6:]) / 6
                if (curr_6 - prev_6) * base > 0:
                    return base + (1 if base > 0 else -1)
            return base

        @staticmethod
        def _mid_from_depth(depth: OrderDepth) -> float | None:
            if depth.buy_orders and depth.sell_orders:
                return (max(depth.buy_orders) + min(depth.sell_orders)) / 2.0
            if depth.buy_orders:
                return float(max(depth.buy_orders))
            if depth.sell_orders:
                return float(min(depth.sell_orders))
            return None

        # ---- pair overlay ------------------------------------------------------

        def _compute_overlay(self, mids: Dict[str, float]) -> Dict[str, int]:
            """Return signed unit bias per product from active pair signals.

            High z = product 'a' is rich vs prediction => short a; hedge leg b
            gets +contrib for beta>0 (positive corr), -contrib for beta<0
            (anti-corr — both legs jointly rich, both should mean-revert down).
            """
            bias: Dict[str, float] = {}
            for a, b, beta, alpha, std, weight in self.PAIR_MODELS:
                ma, mb = mids.get(a), mids.get(b)
                if ma is None or mb is None or std <= 0:
                    continue
                z = (ma - beta * mb - alpha) / std
                if abs(z) < self.Z_ENTRY:
                    continue
                zc = max(-self.Z_MAX, min(self.Z_MAX, z))
                contrib = self.OVERLAY_PER_PAIR * weight * zc / self.Z_MAX
                bias[a] = bias.get(a, 0.0) - contrib
                bias[b] = bias.get(b, 0.0) + contrib * (1.0 if beta > 0 else -1.0)
            return {p: int(round(v)) for p, v in bias.items()}

        # ---- main --------------------------------------------------------------

        def run(self, state: TradingState):
            result: Dict[str, List[Order]] = {}
            conversions = 0

            # Pre-compute mids for the pair overlay
            mids: Dict[str, float] = {}
            for product, depth in state.order_depths.items():
                m = self._mid_from_depth(depth)
                if m is not None:
                    mids[product] = m
            overlay = self._compute_overlay(mids)

            for product, depth in state.order_depths.items():
                family = self.get_family(product)
                orders: List[Order] = []

                best_bid = max(depth.buy_orders) if depth.buy_orders else 10000
                best_ask = min(depth.sell_orders) if depth.sell_orders else 10000
                mid = mids.get(product, (best_bid + best_ask) / 2.0)

                momentum = self.calculate_momentum(product, mid)

                bid_offset = family['base_bid']
                ask_offset = family['base_ask']
                max_pos = family['max_pos']
                vol_scale = family['vol_scale']

                if product in self.WINNER_PRODUCTS:
                    adj = self.WINNER_PRODUCTS[product]
                    max_pos = int(max_pos * adj['max_pos_mult'])
                    vol_scale = vol_scale * adj['vol_mult']
                elif product in self.LOSER_PRODUCTS:
                    adj = self.LOSER_PRODUCTS[product]
                    max_pos = int(max_pos * adj['max_pos_mult'])
                    vol_scale = vol_scale * adj['vol_mult']
                    bid_offset = int(bid_offset * adj['offset_mult'])
                    ask_offset = int(ask_offset * adj['offset_mult'])

                # Momentum: tighten on the side of the move
                if momentum >= 2:
                    bid_offset = max(bid_offset - 2, -6)
                    ask_offset = max(ask_offset - 1, -4)
                elif momentum == 1:
                    bid_offset = max(bid_offset - 1, -5)
                elif momentum <= -2:
                    ask_offset = min(ask_offset + 2, 6)
                    bid_offset = min(bid_offset + 1, 4)
                elif momentum == -1:
                    ask_offset = min(ask_offset + 1, 5)

                bid_vol = max(1, int((list(depth.buy_orders.values())[0] if depth.buy_orders else 10) * vol_scale))
                ask_vol = max(1, int((list(depth.sell_orders.values())[0] if depth.sell_orders else 10) * vol_scale))

                bid_price = int(mid) + bid_offset
                ask_price = int(mid) + ask_offset

                current_pos = state.position.get(product, 0)
                extra = overlay.get(product, 0)

                if current_pos < max_pos:
                    orders.append(Order(product, bid_price, bid_vol))
                if current_pos > -max_pos:
                    orders.append(Order(product, ask_price, ask_vol))

                # Pair overlay: passive limit orders inside the spread (one tick
                # better than our MM quote). Sized small (OVERLAY_PER_PAIR), so we
                # can't blow through MM economics.
                if extra > 0:
                    size = min(extra, max_pos - current_pos)
                    if size > 0:
                        overlay_bid = bid_price + 1
                        if overlay_bid < best_ask:
                            orders.append(Order(product, overlay_bid, size))
                elif extra < 0:
                    size = min(-extra, current_pos + max_pos)
                    if size > 0:
                        overlay_ask = ask_price - 1
                        if overlay_ask > best_bid:
                            orders.append(Order(product, overlay_ask, -size))

                result[product] = orders

            return result, conversions, ""

    __m = __CompiledModule()
    for __k, __v in list(locals().items()):
        if not __k.startswith('__'):
            setattr(__m, __k, __v)
    return __m

trader_combined_strats = __build_trader_combined_strats()
traders.ROUND_5.trader_combined_strats = trader_combined_strats
# --- end pasted traders/ROUND_5/trader_combined_strats.py ---

Trader = trader_combined_strats.Trader

__all__ = ['Trader']
